/**
 * Data de lanzamientos sincronizada 1:1 con Record Club (https://record.club/releases?sortBy=popularity-week)
 * Incluye los 84 lanzamientos completos de 'Popularity this week' con sus artworks y metadatos verificados.
 */

export const RECORD_CLUB_FALLBACK_RELEASES = [
  {
    "id": "z59oke9jznqlv6wq",
    "album_name": "PRIMA",
    "artist_name": "ADÉLA",
    "image_url": "https://cdn.rcrd.club/releases/z59oke9jznqlv6wq.webp?width=500",
    "release_date": "2026-09-04",
    "release_type": "ALBUM",
    "total_tracks": 12,
    "trending_rank": 1,
    "popularity_raw": 442,
    "popularity_this_week": "442 pts",
    "genre_category": "POP / ALTERNATIVE",
    "badge": "🔥 #1 Popularity This Week",
    "is_new": true,
    "record_club_url": "https://record.club/releases/albums/adela-prima"
  },
  {
    "id": "01d4kvym22ok76m2",
    "album_name": "Age of the Exhibitionist",
    "artist_name": "Rebecca Black",
    "image_url": "https://cdn.rcrd.club/releases/01d4kvym22ok76m2.webp?width=500",
    "release_date": "2026-09-04",
    "release_type": "ALBUM",
    "total_tracks": 12,
    "trending_rank": 2,
    "popularity_raw": 344,
    "popularity_this_week": "344 pts",
    "genre_category": "HYPERPOP",
    "badge": "Top 3 Global",
    "is_new": true,
    "record_club_url": "https://record.club/releases/albums/rebecca-black-age-of-the-exibitionist"
  },
  {
    "id": "vge38jdd76z8n6md",
    "album_name": "Who Loves the Sun",
    "artist_name": "Chat Pile",
    "image_url": "https://cdn.rcrd.club/releases/vge38jdd76z8n6md/mv6nknj2vyv8qxod.webp?v=45345827278&width=500",
    "release_date": "2026-09-04",
    "release_type": "ALBUM",
    "total_tracks": 12,
    "trending_rank": 3,
    "popularity_raw": 275,
    "popularity_this_week": "275 pts",
    "genre_category": "SLUDGE / NOISE ROCK",
    "badge": "Top 3 Global",
    "is_new": true,
    "record_club_url": "https://record.club/releases/albums/chat-pile-who-loves-the-sun"
  },
  {
    "id": "3qe68y0657wlrv01",
    "album_name": "you seem pretty sad for a girl so in love",
    "artist_name": "Olivia Rodrigo",
    "image_url": "https://cdn.rcrd.club/releases/3qe68y0657wlrv01/zq95kmxgy7o8rvdg.webp?v=44762127501&width=500",
    "release_date": "2026-06-12",
    "release_type": "ALBUM",
    "total_tracks": 12,
    "trending_rank": 4,
    "popularity_raw": 227,
    "popularity_this_week": "227 pts",
    "genre_category": "POP ROCK",
    "badge": "Tendencia Semanal",
    "is_new": false,
    "record_club_url": "https://record.club/releases/albums/olivia-rodrigo-you-seem-pretty-sad-for-a-girl-so-in-love"
  },
  {
    "id": "mv6nknr3x4nlqxod",
    "album_name": "Lost Weekend",
    "artist_name": "Phoebe Bridgers",
    "image_url": "https://cdn.rcrd.club/releases/mv6nknr3x4nlqxod/3wxr86q0p4dl2gny.webp?v=45784166404&width=500",
    "release_date": "2026-08-14",
    "release_type": "ALBUM",
    "total_tracks": 12,
    "trending_rank": 5,
    "popularity_raw": 216,
    "popularity_this_week": "216 pts",
    "genre_category": "INDIE FOLK",
    "badge": "Tendencia Semanal",
    "is_new": false,
    "record_club_url": "https://record.club/releases/albums/phoebe-bridgers-lost-weekend"
  },
  {
    "id": "2gpqkx5dm4j83r45",
    "album_name": "Music, Fashion, Film",
    "artist_name": "Charli xcx",
    "image_url": "https://cdn.rcrd.club/releases/2gpqkx5dm4j83r45/ry7v833zrny8x9z0.webp?v=45279077084&width=500",
    "release_date": "2026-07-24",
    "release_type": "ALBUM",
    "total_tracks": 12,
    "trending_rank": 6,
    "popularity_raw": 162,
    "popularity_this_week": "162 pts",
    "genre_category": "HYPERPOP / CLUB",
    "badge": "Tendencia Semanal",
    "is_new": false,
    "record_club_url": "https://record.club/releases/albums/charli-xcx-music-fashion-film"
  },
  {
    "id": "5wyz8d5mrd7kxve9",
    "album_name": "WOR$T GIRL IN AMERICA",
    "artist_name": "Slayyyter",
    "image_url": "https://cdn.rcrd.club/releases/5wyz8d5mrd7kxve9/2gpqkxzyp1o83r45.webp?v=44080257335&width=500",
    "release_date": "2026-03-27",
    "release_type": "ALBUM",
    "total_tracks": 12,
    "trending_rank": 7,
    "popularity_raw": 155,
    "popularity_this_week": "155 pts",
    "genre_category": "ELECTROPOP",
    "badge": "Tendencia Semanal",
    "is_new": false,
    "record_club_url": "https://record.club/releases/albums/slayyyter-wor-t-girl-in-america"
  },
  {
    "id": "ry7v83w4o7jlx9z0",
    "album_name": "U",
    "artist_name": "underscores",
    "image_url": "https://cdn.rcrd.club/releases/ry7v83w4o7jlx9z0/zgrel4617egkv319.webp?v=44651354753&width=500",
    "release_date": "2026-03-20",
    "release_type": "ALBUM",
    "total_tracks": 12,
    "trending_rank": 8,
    "popularity_raw": 120,
    "popularity_this_week": "120 pts",
    "genre_category": "HYPERPOP / INDIE",
    "badge": "Tendencia Semanal",
    "is_new": false,
    "record_club_url": "https://record.club/releases/albums/underscores-u"
  },
  {
    "id": "v9yq8wq4qjp8451e",
    "album_name": "It Goes On",
    "artist_name": "Westside Cowboy",
    "image_url": "https://cdn.rcrd.club/releases/v9yq8wq4qjp8451e/zq95kmxzv738rvdg.webp?v=45176529471&width=500",
    "release_date": "2026-08-21",
    "release_type": "ALBUM",
    "total_tracks": 12,
    "trending_rank": 9,
    "popularity_raw": 120,
    "popularity_this_week": "120 pts",
    "genre_category": "INDIE ROCK",
    "badge": "Tendencia Semanal",
    "is_new": false,
    "record_club_url": "https://record.club/releases/albums/westside-cowboy-it-goes-on"
  },
  {
    "id": "01d4kvdmydok76m2",
    "album_name": "Nothing’s About to Happen to Me",
    "artist_name": "Mitski",
    "image_url": "https://cdn.rcrd.club/releases/01d4kvdmydok76m2/r5eoko4ew6ql61n4.webp?v=44186539920&width=500",
    "release_date": "2026-02-27",
    "release_type": "ALBUM",
    "total_tracks": 12,
    "trending_rank": 10,
    "popularity_raw": 114,
    "popularity_this_week": "114 pts",
    "genre_category": "INDIE ROCK",
    "badge": "Tendencia Semanal",
    "is_new": false,
    "record_club_url": "https://record.club/releases/albums/mitski-nothings-about-to-happen-to-me"
  },
  {
    "id": "0592lpzd759841r6",
    "album_name": "Oh yeah?",
    "artist_name": "Steve Lacy",
    "image_url": "https://cdn.rcrd.club/releases/0592lpzd759841r6.webp?width=500",
    "release_date": "2026-07-17",
    "release_type": "ALBUM",
    "total_tracks": 12,
    "trending_rank": 11,
    "popularity_raw": 114,
    "popularity_this_week": "114 pts",
    "genre_category": "R&B / NEO-SOUL",
    "badge": "Tendencia Semanal",
    "is_new": false,
    "record_club_url": "https://record.club/releases/albums/steve-lacy-oh-yeah"
  },
  {
    "id": "ry7v83w63w0lx9z0",
    "album_name": "petal",
    "artist_name": "Ariana Grande",
    "image_url": "https://cdn.rcrd.club/releases/ry7v83w63w0lx9z0/1dezk96d6qpkxyq9.webp?v=44987904469&width=500",
    "release_date": "2026-07-31",
    "release_type": "ALBUM",
    "total_tracks": 12,
    "trending_rank": 12,
    "popularity_raw": 111,
    "popularity_this_week": "111 pts",
    "genre_category": "POP / R&B",
    "badge": "Tendencia Semanal",
    "is_new": false,
    "record_club_url": "https://record.club/releases/albums/ariana-grande-petal"
  },
  {
    "id": "v9yq8wqnqrp8451e",
    "album_name": "ii",
    "artist_name": "Denzel Curry & Kenny Beats",
    "image_url": "https://cdn.rcrd.club/releases/v9yq8wqnqrp8451e.webp?width=500",
    "release_date": "2026-08-21",
    "release_type": "ALBUM",
    "total_tracks": 12,
    "trending_rank": 13,
    "popularity_raw": 110,
    "popularity_this_week": "110 pts",
    "genre_category": "HIP-HOP",
    "badge": "Tendencia Semanal",
    "is_new": false,
    "record_club_url": "https://record.club/releases/albums/denzel-curry-kenny-beats-ii"
  },
  {
    "id": "ox4n879oz71ldpez",
    "album_name": "Happier Now",
    "artist_name": "Movements",
    "image_url": "https://cdn.rcrd.club/releases/ox4n879oz71ldpez.webp?width=500",
    "release_date": "2026-09-04",
    "release_type": "ALBUM",
    "total_tracks": 12,
    "trending_rank": 14,
    "popularity_raw": 100,
    "popularity_this_week": "100 pts",
    "genre_category": "POST-HARDCORE / EMO",
    "badge": "NEW",
    "is_new": true,
    "record_club_url": "https://record.club/releases/albums/movements-happier-now"
  },
  {
    "id": "r5eokoeewvq861n4",
    "album_name": "This Mirror Weighs a Ton",
    "artist_name": "Interpol",
    "image_url": "https://cdn.rcrd.club/releases/r5eokoeewvq861n4.webp?width=500",
    "release_date": "2026-08-28",
    "release_type": "ALBUM",
    "total_tracks": 12,
    "trending_rank": 15,
    "popularity_raw": 96,
    "popularity_this_week": "96 pts",
    "genre_category": "POST-PUNK",
    "badge": "Tendencia Semanal",
    "is_new": false,
    "record_club_url": "https://record.club/releases/albums/interpol-this-mirror-weighs-a-ton"
  },
  {
    "id": "mv6nkndge4g8qxod",
    "album_name": "The Mountain",
    "artist_name": "Gorillaz",
    "image_url": "https://cdn.rcrd.club/releases/mv6nkndge4g8qxod/3qe68y7gd5w8rv01.webp?v=44466996180&width=500",
    "release_date": "2026-02-27",
    "release_type": "ALBUM",
    "total_tracks": 12,
    "trending_rank": 16,
    "popularity_raw": 87,
    "popularity_this_week": "87 pts",
    "genre_category": "ART POP / ALTERNATIVE",
    "badge": "Tendencia Semanal",
    "is_new": false,
    "record_club_url": "https://record.club/releases/albums/gorillaz-the-mountain"
  },
  {
    "id": "nvj0kz6wv6vld3rm",
    "album_name": "Marrow Deep",
    "artist_name": "Mastodon",
    "image_url": "https://cdn.rcrd.club/releases/nvj0kz6wv6vld3rm.webp?width=500",
    "release_date": "2026-08-28",
    "release_type": "ALBUM",
    "total_tracks": 12,
    "trending_rank": 17,
    "popularity_raw": 86,
    "popularity_this_week": "86 pts",
    "genre_category": "PROGRESSIVE METAL",
    "badge": "Tendencia Semanal",
    "is_new": false,
    "record_club_url": "https://record.club/releases/albums/mastodon-marrow-deep"
  },
  {
    "id": "32j5gkrv5r3l1yp4",
    "album_name": "OK Computer",
    "artist_name": "Radiohead",
    "image_url": "https://cdn.rcrd.club/releases/32j5gkrv5r3l1yp4/0592lp5zynn841r6.webp?v=43287476628&width=500",
    "release_date": "1997-05-21",
    "release_type": "ALBUM",
    "total_tracks": 12,
    "trending_rank": 18,
    "popularity_raw": 82,
    "popularity_this_week": "82 pts",
    "genre_category": "ART ROCK",
    "badge": "Tendencia Semanal",
    "is_new": false,
    "record_club_url": "https://record.club/releases/albums/radiohead-ok-computer"
  },
  {
    "id": "01d4kvd11evk76m2",
    "album_name": "Wuthering Heights",
    "artist_name": "Charli xcx",
    "image_url": "https://cdn.rcrd.club/releases/01d4kvd11evk76m2/zq95km2xjx9lrvdg.webp?v=44341283981&width=500",
    "release_date": "2026-02-13",
    "release_type": "ALBUM",
    "total_tracks": 12,
    "trending_rank": 19,
    "popularity_raw": 81,
    "popularity_this_week": "81 pts",
    "genre_category": "HYPERPOP / CLUB",
    "badge": "Tendencia Semanal",
    "is_new": false,
    "record_club_url": "https://record.club/releases/albums/charli-xcx-wuthering-heights"
  },
  {
    "id": "3wxr8639pno82gny",
    "album_name": "lucy miró al mundo y notó que está girando",
    "artist_name": "AKRIILA",
    "image_url": "https://cdn.rcrd.club/releases/3wxr8639pno82gny.webp?width=500",
    "release_date": "2026-09-03",
    "release_type": "ALBUM",
    "total_tracks": 12,
    "trending_rank": 20,
    "popularity_raw": 81,
    "popularity_this_week": "81 pts",
    "genre_category": "URBANO / TRAP",
    "badge": "NEW",
    "is_new": true,
    "record_club_url": "https://record.club/releases/albums/akriila-lucy-miro-al-mundo-y-noto-que-esta-girando"
  },
  {
    "id": "ox4n87739mx8dpez",
    "album_name": "THIS MUSIC MAY CONTAIN HOPE.",
    "artist_name": "Raye",
    "image_url": "https://cdn.rcrd.club/releases/ox4n87739mx8dpez.webp?width=500",
    "release_date": "2026-03-27",
    "release_type": "ALBUM",
    "total_tracks": 12,
    "trending_rank": 21,
    "popularity_raw": 79,
    "popularity_this_week": "79 pts",
    "genre_category": "R&B / POP",
    "badge": "Tendencia Semanal",
    "is_new": false,
    "record_club_url": "https://record.club/releases/albums/raye-this-music-may-contain-hope"
  },
  {
    "id": "5nm7l0wejx7key69",
    "album_name": "Reality Awaits",
    "artist_name": "The Strokes",
    "image_url": "https://cdn.rcrd.club/releases/5nm7l0wejx7key69/r5eokogjo4ql61n4.webp?v=44864216062&width=500",
    "release_date": "2026-07-24",
    "release_type": "ALBUM",
    "total_tracks": 12,
    "trending_rank": 22,
    "popularity_raw": 78,
    "popularity_this_week": "78 pts",
    "genre_category": "GARAGE ROCK",
    "badge": "Tendencia Semanal",
    "is_new": false,
    "record_club_url": "https://record.club/releases/albums/the-strokes-reality-awaits"
  },
  {
    "id": "z59oke95y70lv6wq",
    "album_name": "Inferno",
    "artist_name": "Boards of Canada",
    "image_url": "https://cdn.rcrd.club/releases/z59oke95y70lv6wq/ox4n875d4o4kdpez.webp?v=44933774153&width=500",
    "release_date": "2026-05-28",
    "release_type": "ALBUM",
    "total_tracks": 12,
    "trending_rank": 23,
    "popularity_raw": 78,
    "popularity_this_week": "78 pts",
    "genre_category": "IDM / AMBIENT",
    "badge": "Tendencia Semanal",
    "is_new": false,
    "record_club_url": "https://record.club/releases/albums/boards-of-canada-inferno"
  },
  {
    "id": "9321859qw06kpo7m",
    "album_name": "Before the World Blows",
    "artist_name": "Erykah Badu & The Alchemist",
    "image_url": "https://cdn.rcrd.club/releases/9321859qw06kpo7m.webp?width=500",
    "release_date": "2026-08-28",
    "release_type": "ALBUM",
    "total_tracks": 12,
    "trending_rank": 24,
    "popularity_raw": 78,
    "popularity_this_week": "78 pts",
    "genre_category": "NEO-SOUL / HIP-HOP",
    "badge": "Tendencia Semanal",
    "is_new": false,
    "record_club_url": "https://record.club/releases/albums/erykah-badu-the-alchemist-before-the-world-blows"
  },
  {
    "id": "ox4n8779w138dpez",
    "album_name": "Don’t Be Dumb",
    "artist_name": "A$AP Rocky",
    "image_url": "https://cdn.rcrd.club/releases/ox4n8779w138dpez/5wyz8d6rg40lxve9.webp?v=43881347221&width=500",
    "release_date": "2026-01-16",
    "release_type": "ALBUM",
    "total_tracks": 12,
    "trending_rank": 25,
    "popularity_raw": 77,
    "popularity_this_week": "77 pts",
    "genre_category": "POP / ALTERNATIVE",
    "badge": "Tendencia Semanal",
    "is_new": false,
    "record_club_url": "https://record.club/releases/albums/a-ap-rocky-dont-be-dumb"
  },
  {
    "id": "0592lpz216n841r6",
    "album_name": "Cry Baby",
    "artist_name": "Vince Staples",
    "image_url": "https://cdn.rcrd.club/releases/0592lpz216n841r6/zq95kmx4eo28rvdg.webp?v=44982256935&width=500",
    "release_date": "2026-06-05",
    "release_type": "ALBUM",
    "total_tracks": 12,
    "trending_rank": 26,
    "popularity_raw": 77,
    "popularity_this_week": "77 pts",
    "genre_category": "HIP-HOP",
    "badge": "Tendencia Semanal",
    "is_new": false,
    "record_club_url": "https://record.club/releases/albums/vince-staples-cry-baby"
  },
  {
    "id": "znp5kgexyexlvx3q",
    "album_name": "I Know Too Much",
    "artist_name": "Ellie Goulding",
    "image_url": "https://cdn.rcrd.club/releases/znp5kgexyexlvx3q/ox4n875zor4kdpez.webp?v=45308852883&width=500",
    "release_date": "2026-09-04",
    "release_type": "ALBUM",
    "total_tracks": 12,
    "trending_rank": 27,
    "popularity_raw": 77,
    "popularity_this_week": "77 pts",
    "genre_category": "ELECTROPOP",
    "badge": "NEW",
    "is_new": true,
    "record_club_url": "https://record.club/releases/albums/ellie-goulding-i-know-too-much"
  },
  {
    "id": "05golq0w0r481j23",
    "album_name": "In Rainbows",
    "artist_name": "Radiohead",
    "image_url": "https://cdn.rcrd.club/releases/05golq0w0r481j23/gmv6nkn0n45lqxod.webp?v=6689244510&width=500",
    "release_date": "2007-10-10",
    "release_type": "ALBUM",
    "total_tracks": 12,
    "trending_rank": 28,
    "popularity_raw": 76,
    "popularity_this_week": "76 pts",
    "genre_category": "ART ROCK",
    "badge": "Tendencia Semanal",
    "is_new": false,
    "record_club_url": "https://record.club/releases/albums/radiohead-in-rainbows"
  },
  {
    "id": "yze2k102w3m840wq",
    "album_name": "Kiss All the Time. Disco, Occasionally.",
    "artist_name": "Harry Styles",
    "image_url": "https://cdn.rcrd.club/releases/yze2k102w3m840wq/yze2k1qe4jol40wq.webp?v=44528415048&width=500",
    "release_date": "2026-03-06",
    "release_type": "ALBUM",
    "total_tracks": 12,
    "trending_rank": 29,
    "popularity_raw": 76,
    "popularity_this_week": "76 pts",
    "genre_category": "POP / GLAM ROCK",
    "badge": "Tendencia Semanal",
    "is_new": false,
    "record_club_url": "https://record.club/releases/albums/harry-styles-kiss-all-the-time-disco-occasionally"
  },
  {
    "id": "25zegl23ond84ymq",
    "album_name": "Rumours",
    "artist_name": "Fleetwood Mac",
    "image_url": "https://cdn.rcrd.club/releases/25zegl23ond84ymq/r5eokoj0qmgl61n4.webp?v=7946930592&width=500",
    "release_date": "1977-02-04",
    "release_type": "ALBUM",
    "total_tracks": 12,
    "trending_rank": 30,
    "popularity_raw": 72,
    "popularity_this_week": "72 pts",
    "genre_category": "CLASSIC ROCK",
    "badge": "Tendencia Semanal",
    "is_new": false,
    "record_club_url": "https://record.club/releases/albums/fleetwood-mac-rumours"
  },
  {
    "id": "nzq95kmz12lrvdgw",
    "album_name": "Wish You Were Here",
    "artist_name": "Pink Floyd",
    "image_url": "https://cdn.rcrd.club/releases/nzq95kmz12lrvdgw.webp?width=500",
    "release_date": "1975-09-12",
    "release_type": "ALBUM",
    "total_tracks": 12,
    "trending_rank": 31,
    "popularity_raw": 70,
    "popularity_this_week": "70 pts",
    "genre_category": "PSYCHEDELIC ROCK",
    "badge": "Tendencia Semanal",
    "is_new": false,
    "record_club_url": "https://record.club/releases/albums/pink-floyd-wish-you-were-here"
  },
  {
    "id": "3qe68y0n71rlrv01",
    "album_name": "new avatar",
    "artist_name": "Kelela",
    "image_url": "https://cdn.rcrd.club/releases/3qe68y0n71rlrv01/zgrel44pqzwlv319.webp?v=45056678231&width=500",
    "release_date": "2026-07-10",
    "release_type": "ALBUM",
    "total_tracks": 12,
    "trending_rank": 32,
    "popularity_raw": 69,
    "popularity_this_week": "69 pts",
    "genre_category": "ALTERNATIVE R&B",
    "badge": "Tendencia Semanal",
    "is_new": false,
    "record_club_url": "https://record.club/releases/albums/kelela-new-avatar"
  },
  {
    "id": "zgrel4rvr24kv319",
    "album_name": "Half-Told Tales",
    "artist_name": "Arab Strap",
    "image_url": "https://cdn.rcrd.club/releases/zgrel4rvr24kv319.webp?width=500",
    "release_date": "2026-09-04",
    "release_type": "ALBUM",
    "total_tracks": 12,
    "trending_rank": 33,
    "popularity_raw": 69,
    "popularity_this_week": "69 pts",
    "genre_category": "SLOWCORE / INDIE",
    "badge": "NEW",
    "is_new": true,
    "record_club_url": "https://record.club/releases/albums/arab-strap-half-told-tales"
  },
  {
    "id": "qr5eokopr5gl61n4",
    "album_name": "Remain in Light",
    "artist_name": "Talking Heads",
    "image_url": "https://cdn.rcrd.club/releases/qr5eokopr5gl61n4/x01d4kv511l76m2r.webp?v=41876738081&width=500",
    "release_date": "1980-10-08",
    "release_type": "ALBUM",
    "total_tracks": 12,
    "trending_rank": 34,
    "popularity_raw": 68,
    "popularity_this_week": "68 pts",
    "genre_category": "NEW WAVE",
    "badge": "Tendencia Semanal",
    "is_new": false,
    "record_club_url": "https://record.club/releases/albums/talking-heads-remain-in-light"
  },
  {
    "id": "5nm7l0pdnnd8ey69",
    "album_name": "The Dark Side of the Moon",
    "artist_name": "Pink Floyd",
    "image_url": "https://cdn.rcrd.club/releases/5nm7l0pdnnd8ey69/zgrel40v1g4kv319.webp?v=34025419985&width=500",
    "release_date": "1973-03-24",
    "release_type": "ALBUM",
    "total_tracks": 12,
    "trending_rank": 35,
    "popularity_raw": 68,
    "popularity_this_week": "68 pts",
    "genre_category": "PSYCHEDELIC ROCK",
    "badge": "Tendencia Semanal",
    "is_new": false,
    "record_club_url": "https://record.club/releases/albums/pink-floyd-the-dark-side-of-the-moon"
  },
  {
    "id": "01d4kvdoejyk76m2",
    "album_name": "Ca$ino",
    "artist_name": "Baby Keem",
    "image_url": "https://cdn.rcrd.club/releases/01d4kvdoejyk76m2/znp5kggg1dxkvx3q.webp?v=44477470449&width=500",
    "release_date": "2026-02-20",
    "release_type": "ALBUM",
    "total_tracks": 12,
    "trending_rank": 36,
    "popularity_raw": 68,
    "popularity_this_week": "68 pts",
    "genre_category": "HIP-HOP",
    "badge": "Tendencia Semanal",
    "is_new": false,
    "record_club_url": "https://record.club/releases/albums/baby-keem-ca-ino"
  },
  {
    "id": "3wxr86xe1po82gny",
    "album_name": "To Pimp a Butterfly",
    "artist_name": "Kendrick Lamar",
    "image_url": "https://cdn.rcrd.club/releases/3wxr86xe1po82gny/5wyz8dzmgw0kxve9.webp?v=45334112812&width=500",
    "release_date": "2015-03-15",
    "release_type": "ALBUM",
    "total_tracks": 12,
    "trending_rank": 37,
    "popularity_raw": 67,
    "popularity_this_week": "67 pts",
    "genre_category": "CONSCIOUS HIP-HOP",
    "badge": "Tendencia Semanal",
    "is_new": false,
    "record_club_url": "https://record.club/releases/albums/kendrick-lamar-to-pimp-a-butterfly"
  },
  {
    "id": "zq95kmeyqy9lrvdg",
    "album_name": "Detour",
    "artist_name": "Kim Petras",
    "image_url": "https://cdn.rcrd.club/releases/zq95kmeyqy9lrvdg/r5eokogn7wml61n4.webp?v=45237028400&width=500",
    "release_date": "2026-05-29",
    "release_type": "ALBUM",
    "total_tracks": 12,
    "trending_rank": 38,
    "popularity_raw": 67,
    "popularity_this_week": "67 pts",
    "genre_category": "DANCE-POP",
    "badge": "Tendencia Semanal",
    "is_new": false,
    "record_club_url": "https://record.club/releases/albums/kim-petras-detour"
  },
  {
    "id": "qr5eoko1dgql61n4",
    "album_name": "The Bends",
    "artist_name": "Radiohead",
    "image_url": "https://cdn.rcrd.club/releases/qr5eoko1dgql61n4/mv6nknn6vnrkqxod.webp?v=32251121765&width=500",
    "release_date": "1995-03-08",
    "release_type": "ALBUM",
    "total_tracks": 12,
    "trending_rank": 39,
    "popularity_raw": 66,
    "popularity_this_week": "66 pts",
    "genre_category": "ART ROCK",
    "badge": "Tendencia Semanal",
    "is_new": false,
    "record_club_url": "https://record.club/releases/albums/radiohead-the-bends"
  },
  {
    "id": "mv6nkndjd158qxod",
    "album_name": "The Romantic",
    "artist_name": "Bruno Mars",
    "image_url": "https://cdn.rcrd.club/releases/mv6nkndjd158qxod.webp?width=500",
    "release_date": "2026-02-27",
    "release_type": "ALBUM",
    "total_tracks": 12,
    "trending_rank": 40,
    "popularity_raw": 66,
    "popularity_this_week": "66 pts",
    "genre_category": "R&B / SOUL",
    "badge": "Tendencia Semanal",
    "is_new": false,
    "record_club_url": "https://record.club/releases/albums/bruno-mars-the-romantic"
  },
  {
    "id": "r5eokoqx7dd861n4",
    "album_name": "Blonde",
    "artist_name": "Frank Ocean",
    "image_url": "https://cdn.rcrd.club/releases/r5eokoqx7dd861n4/05golq36yj481j23.webp?v=14420632959&width=500",
    "release_date": "2016-08-20",
    "release_type": "ALBUM",
    "total_tracks": 12,
    "trending_rank": 41,
    "popularity_raw": 63,
    "popularity_this_week": "63 pts",
    "genre_category": "R&B / SOUL",
    "badge": "Tendencia Semanal",
    "is_new": false,
    "record_club_url": "https://record.club/releases/albums/frank-ocean-blonde"
  },
  {
    "id": "05golqeprr4l1j23",
    "album_name": "CONFESSIONS II",
    "artist_name": "Madonna",
    "image_url": "https://cdn.rcrd.club/releases/05golqeprr4l1j23/znp5kg4wvpjkvx3q.webp?v=44874066341&width=500",
    "release_date": "2026-07-03",
    "release_type": "ALBUM",
    "total_tracks": 12,
    "trending_rank": 42,
    "popularity_raw": 63,
    "popularity_this_week": "63 pts",
    "genre_category": "DANCE-POP",
    "badge": "Tendencia Semanal",
    "is_new": false,
    "record_club_url": "https://record.club/releases/albums/madonna-confessions-ii"
  },
  {
    "id": "6nvj0kz0dm5ld3rm",
    "album_name": "Nevermind",
    "artist_name": "Nirvana",
    "image_url": "https://cdn.rcrd.club/releases/6nvj0kz0dm5ld3rm/3wxr864nvx7k2gny.webp?v=30501372565&width=500",
    "release_date": "1991-09-24",
    "release_type": "ALBUM",
    "total_tracks": 12,
    "trending_rank": 43,
    "popularity_raw": 62,
    "popularity_this_week": "62 pts",
    "genre_category": "GRUNGE",
    "badge": "Tendencia Semanal",
    "is_new": false,
    "record_club_url": "https://record.club/releases/albums/nirvana-nevermind"
  },
  {
    "id": "zq95kmemro3lrvdg",
    "album_name": "REDSTAR WU & THE WORLDWIDE SCOURGE",
    "artist_name": "Genesis Owusu",
    "image_url": "https://cdn.rcrd.club/releases/zq95kmemro3lrvdg/932185yqvoolpo7m.webp?v=44712158870&width=500",
    "release_date": "2026-05-15",
    "release_type": "ALBUM",
    "total_tracks": 12,
    "trending_rank": 44,
    "popularity_raw": 61,
    "popularity_this_week": "61 pts",
    "genre_category": "EXPERIMENTAL R&B",
    "badge": "Tendencia Semanal",
    "is_new": false,
    "record_club_url": "https://record.club/releases/albums/genesis-owusu-redstar-wu-the-worldwide-scourge"
  },
  {
    "id": "oznp5kg2oe3lvx3q",
    "album_name": "Grace",
    "artist_name": "Jeff Buckley",
    "image_url": "https://cdn.rcrd.club/releases/oznp5kg2oe3lvx3q/qr5eoko9ynqk61n4.webp?v=24008507233&width=500",
    "release_date": "1994-08-15",
    "release_type": "ALBUM",
    "total_tracks": 12,
    "trending_rank": 45,
    "popularity_raw": 60,
    "popularity_this_week": "60 pts",
    "genre_category": "ALTERNATIVE ROCK",
    "badge": "Tendencia Semanal",
    "is_new": false,
    "record_club_url": "https://record.club/releases/albums/jeff-buckley-grace"
  },
  {
    "id": "ry7v83wd3x6lx9z0",
    "album_name": "HALO",
    "artist_name": "Tiffany Day",
    "image_url": "https://cdn.rcrd.club/releases/ry7v83wd3x6lx9z0/r5eoko423j7l61n4.webp?v=44798679413&width=500",
    "release_date": "2026-04-03",
    "release_type": "ALBUM",
    "total_tracks": 12,
    "trending_rank": 46,
    "popularity_raw": 60,
    "popularity_this_week": "60 pts",
    "genre_category": "BEDROOM POP",
    "badge": "Tendencia Semanal",
    "is_new": false,
    "record_club_url": "https://record.club/releases/albums/tiffany-day-ha-o"
  },
  {
    "id": "01d4kvdzdwek76m2",
    "album_name": "Trying Times",
    "artist_name": "James Blake",
    "image_url": "https://cdn.rcrd.club/releases/01d4kvdzdwek76m2/zgrel46jvzjkv319.webp?v=44936054854&width=500",
    "release_date": "2026-03-13",
    "release_type": "ALBUM",
    "total_tracks": 12,
    "trending_rank": 47,
    "popularity_raw": 59,
    "popularity_this_week": "59 pts",
    "genre_category": "ELECTRONIC / SOUL",
    "badge": "Tendencia Semanal",
    "is_new": false,
    "record_club_url": "https://record.club/releases/albums/james-blake-trying-times"
  },
  {
    "id": "nvj0kz3o54pld3rm",
    "album_name": "Distracted",
    "artist_name": "Thundercat",
    "image_url": "https://cdn.rcrd.club/releases/nvj0kz3o54pld3rm/v9yq8wgq1ppl451e.webp?v=44218093094&width=500",
    "release_date": "2026-04-03",
    "release_type": "ALBUM",
    "total_tracks": 12,
    "trending_rank": 48,
    "popularity_raw": 59,
    "popularity_this_week": "59 pts",
    "genre_category": "FUNK / JAZZ FUSION",
    "badge": "Tendencia Semanal",
    "is_new": false,
    "record_club_url": "https://record.club/releases/albums/thundercat-distracted"
  },
  {
    "id": "932185wq3n68po7m",
    "album_name": "Vol.II",
    "artist_name": "Angine de Poitrine",
    "image_url": "https://cdn.rcrd.club/releases/932185wq3n68po7m/1dezk97yznvlxyq9.webp?v=44536532463&width=500",
    "release_date": "2026-04-03",
    "release_type": "ALBUM",
    "total_tracks": 12,
    "trending_rank": 49,
    "popularity_raw": 59,
    "popularity_this_week": "59 pts",
    "genre_category": "INDIE ROCK",
    "badge": "Tendencia Semanal",
    "is_new": false,
    "record_club_url": "https://record.club/releases/albums/angine-de-poitrine-vol-ii"
  },
  {
    "id": "vge38jdn5ym8n6md",
    "album_name": "The Fatal Flaw",
    "artist_name": "Paris Paloma",
    "image_url": "https://cdn.rcrd.club/releases/vge38jdn5ym8n6md.webp?width=500",
    "release_date": "2026-09-04",
    "release_type": "ALBUM",
    "total_tracks": 12,
    "trending_rank": 50,
    "popularity_raw": 59,
    "popularity_this_week": "59 pts",
    "genre_category": "INDIE FOLK",
    "badge": "NEW",
    "is_new": true,
    "record_club_url": "https://record.club/releases/albums/paris-paloma-the-fatal-flaw"
  },
  {
    "id": "1dezk9ey3e08xyq9",
    "album_name": "Getting Killed",
    "artist_name": "Geese",
    "image_url": "https://cdn.rcrd.club/releases/1dezk9ey3e08xyq9/v9yq8w01o4wk451e.webp?v=44191806023&width=500",
    "release_date": "2025-09-26",
    "release_type": "ALBUM",
    "total_tracks": 12,
    "trending_rank": 51,
    "popularity_raw": 58,
    "popularity_this_week": "58 pts",
    "genre_category": "INDIE ROCK",
    "badge": "Tendencia Semanal",
    "is_new": false,
    "record_club_url": "https://record.club/releases/albums/geese-getting-killed"
  },
  {
    "id": "yz59oke6wplv6wqm",
    "album_name": "Abbey Road",
    "artist_name": "The Beatles",
    "image_url": "https://cdn.rcrd.club/releases/yz59oke6wplv6wqm/mv6nkn6d76vlqxod.webp?v=39706767821&width=500",
    "release_date": "1969-09-26",
    "release_type": "ALBUM",
    "total_tracks": 12,
    "trending_rank": 52,
    "popularity_raw": 57,
    "popularity_this_week": "57 pts",
    "genre_category": "CLASSIC ROCK",
    "badge": "Tendencia Semanal",
    "is_new": false,
    "record_club_url": "https://record.club/releases/albums/the-beatles-abbey-road"
  },
  {
    "id": "wv9yq8w69pk451en",
    "album_name": "Kid A",
    "artist_name": "Radiohead",
    "image_url": "https://cdn.rcrd.club/releases/wv9yq8w69pk451en/zgrel4gr6pwlv319.webp?v=29475045164&width=500",
    "release_date": "2000-08-03",
    "release_type": "ALBUM",
    "total_tracks": 12,
    "trending_rank": 53,
    "popularity_raw": 57,
    "popularity_this_week": "57 pts",
    "genre_category": "ART ROCK",
    "badge": "Tendencia Semanal",
    "is_new": false,
    "record_club_url": "https://record.club/releases/albums/radiohead-kid-a"
  },
  {
    "id": "zgrel4r2164kv319",
    "album_name": "THERAPY AT THE CLUB",
    "artist_name": "FLO",
    "image_url": "https://cdn.rcrd.club/releases/zgrel4r2164kv319.webp?width=500",
    "release_date": "2026-08-07",
    "release_type": "ALBUM",
    "total_tracks": 12,
    "trending_rank": 54,
    "popularity_raw": 56,
    "popularity_this_week": "56 pts",
    "genre_category": "R&B",
    "badge": "Tendencia Semanal",
    "is_new": false,
    "record_club_url": "https://record.club/releases/albums/flo-therapy-at-the-club-2"
  },
  {
    "id": "nzq95kmxrn98rvdg",
    "album_name": "Is This It",
    "artist_name": "The Strokes",
    "image_url": "https://cdn.rcrd.club/releases/nzq95kmxrn98rvdg/3qe68yrzm10lrv01.webp?v=39829937702&width=500",
    "release_date": "2001-01-27",
    "release_type": "ALBUM",
    "total_tracks": 12,
    "trending_rank": 55,
    "popularity_raw": 55,
    "popularity_this_week": "55 pts",
    "genre_category": "GARAGE ROCK",
    "badge": "Tendencia Semanal",
    "is_new": false,
    "record_club_url": "https://record.club/releases/albums/the-strokes-is-this-it"
  },
  {
    "id": "05golqe1nj9l1j23",
    "album_name": "The Singer in My Band",
    "artist_name": "This Is Lorelei",
    "image_url": "https://cdn.rcrd.club/releases/05golqe1nj9l1j23.webp?width=500",
    "release_date": "2026-09-11",
    "release_type": "ALBUM",
    "total_tracks": 12,
    "trending_rank": 56,
    "popularity_raw": 55,
    "popularity_this_week": "55 pts",
    "genre_category": "INDIE POP",
    "badge": "NEW",
    "is_new": true,
    "record_club_url": "https://record.club/releases/albums/this-is-lorelei-the-singer-in-my-band"
  },
  {
    "id": "v9yq8wwq29w8451e",
    "album_name": "Currents",
    "artist_name": "Tame Impala",
    "image_url": "https://cdn.rcrd.club/releases/v9yq8wwq29w8451e/5wyz8dzxewrkxve9.webp?v=13249592911&width=500",
    "release_date": "2015-07-15",
    "release_type": "ALBUM",
    "total_tracks": 12,
    "trending_rank": 57,
    "popularity_raw": 54,
    "popularity_this_week": "54 pts",
    "genre_category": "PSYCHEDELIC POP",
    "badge": "Tendencia Semanal",
    "is_new": false,
    "record_club_url": "https://record.club/releases/albums/tame-impala-currents"
  },
  {
    "id": "5zegl23r3yj84ymq",
    "album_name": "Pet Sounds",
    "artist_name": "The Beach Boys",
    "image_url": "https://cdn.rcrd.club/releases/5zegl23r3yj84ymq/vge38j6e022ln6md.webp?v=7129384393&width=500",
    "release_date": "1966-05-16",
    "release_type": "ALBUM",
    "total_tracks": 12,
    "trending_rank": 58,
    "popularity_raw": 53,
    "popularity_this_week": "53 pts",
    "genre_category": "CHAMBER POP",
    "badge": "Tendencia Semanal",
    "is_new": false,
    "record_club_url": "https://record.club/releases/albums/the-beach-boys-pet-sounds"
  },
  {
    "id": "vge38j61gy7ln6md",
    "album_name": "good kid, m.A.A.d city",
    "artist_name": "Kendrick Lamar",
    "image_url": "https://cdn.rcrd.club/releases/vge38j61gy7ln6md/mv6nknvx74v8qxod.webp?v=22057643526&width=500",
    "release_date": "2012-10-21",
    "release_type": "ALBUM",
    "total_tracks": 12,
    "trending_rank": 59,
    "popularity_raw": 53,
    "popularity_this_week": "53 pts",
    "genre_category": "CONSCIOUS HIP-HOP",
    "badge": "Tendencia Semanal",
    "is_new": false,
    "record_club_url": "https://record.club/releases/albums/kendrick-lamar-good-kid-m-a-a-d-city"
  },
  {
    "id": "5nm7l0xqv57ley69",
    "album_name": "Imaginal Disk",
    "artist_name": "Magdalena Bay",
    "image_url": "https://cdn.rcrd.club/releases/5nm7l0xqv57ley69/yze2k10jwwv840wq.webp?v=39313937167&width=500",
    "release_date": "2024-08-23",
    "release_type": "ALBUM",
    "total_tracks": 12,
    "trending_rank": 60,
    "popularity_raw": 53,
    "popularity_this_week": "53 pts",
    "genre_category": "SYNTHPOP",
    "badge": "Tendencia Semanal",
    "is_new": false,
    "record_club_url": "https://record.club/releases/albums/magdalena-bay-imaginal-disk"
  },
  {
    "id": "2j5gkrdmdzxl1yp4",
    "album_name": "Sexistential",
    "artist_name": "Robyn",
    "image_url": "https://cdn.rcrd.club/releases/2j5gkrdmdzxl1yp4.webp?width=500",
    "release_date": "2026-03-27",
    "release_type": "ALBUM",
    "total_tracks": 12,
    "trending_rank": 61,
    "popularity_raw": 53,
    "popularity_this_week": "53 pts",
    "genre_category": "ELECTROPOP",
    "badge": "Tendencia Semanal",
    "is_new": false,
    "record_club_url": "https://record.club/releases/albums/robyn-sexistential"
  },
  {
    "id": "41dezk9zpmo8xyq9",
    "album_name": "Rubber Soul",
    "artist_name": "The Beatles",
    "image_url": "https://cdn.rcrd.club/releases/41dezk9zpmo8xyq9/0592lprmdezk41r6.webp?v=32261789232&width=500",
    "release_date": "1965-12-03",
    "release_type": "ALBUM",
    "total_tracks": 12,
    "trending_rank": 62,
    "popularity_raw": 52,
    "popularity_this_week": "52 pts",
    "genre_category": "CLASSIC ROCK",
    "badge": "Tendencia Semanal",
    "is_new": false,
    "record_club_url": "https://record.club/releases/albums/the-beatles-rubber-soul"
  },
  {
    "id": "z59oke0o25wlv6wq",
    "album_name": "The Fall-Off",
    "artist_name": "J. Cole",
    "image_url": "https://cdn.rcrd.club/releases/z59oke0o25wlv6wq.webp?width=500",
    "release_date": "2026-02-06",
    "release_type": "ALBUM",
    "total_tracks": 12,
    "trending_rank": 63,
    "popularity_raw": 52,
    "popularity_this_week": "52 pts",
    "genre_category": "HIP-HOP",
    "badge": "Tendencia Semanal",
    "is_new": false,
    "record_club_url": "https://record.club/releases/albums/j-cole-the-fall-off"
  },
  {
    "id": "01d4kvd7dzmk76m2",
    "album_name": "locket",
    "artist_name": "Madison Beer",
    "image_url": "https://cdn.rcrd.club/releases/01d4kvd7dzmk76m2/2j5gkr3g75nk1yp4.webp?v=43362451235&width=500",
    "release_date": "2026-01-16",
    "release_type": "ALBUM",
    "total_tracks": 12,
    "trending_rank": 64,
    "popularity_raw": 51,
    "popularity_this_week": "51 pts",
    "genre_category": "POP",
    "badge": "Tendencia Semanal",
    "is_new": false,
    "record_club_url": "https://record.club/releases/albums/madison-beer-locket"
  },
  {
    "id": "932185g4355lpo7m",
    "album_name": "the apple tree under the sea",
    "artist_name": "hemlocke springs",
    "image_url": "https://cdn.rcrd.club/releases/932185g4355lpo7m.webp?width=500",
    "release_date": "2026-02-13",
    "release_type": "ALBUM",
    "total_tracks": 12,
    "trending_rank": 65,
    "popularity_raw": 51,
    "popularity_this_week": "51 pts",
    "genre_category": "INDIE POP",
    "badge": "Tendencia Semanal",
    "is_new": false,
    "record_club_url": "https://record.club/releases/albums/hemlocke-springs-the-apple-tree-under-the-sea"
  },
  {
    "id": "0592lpz4179841r6",
    "album_name": "Blue Island",
    "artist_name": "Ravyn Lenae",
    "image_url": "https://cdn.rcrd.club/releases/0592lpz4179841r6.webp?width=500",
    "release_date": "2026-08-07",
    "release_type": "ALBUM",
    "total_tracks": 12,
    "trending_rank": 66,
    "popularity_raw": 51,
    "popularity_this_week": "51 pts",
    "genre_category": "R&B",
    "badge": "Tendencia Semanal",
    "is_new": false,
    "record_club_url": "https://record.club/releases/albums/ravyn-lenae-blue-island"
  },
  {
    "id": "932185wg0368po7m",
    "album_name": "Weezer",
    "artist_name": "Weezer",
    "image_url": "https://cdn.rcrd.club/releases/932185wg0368po7m/zq95kmxyzzm8rvdg.webp?v=45298277600&width=500",
    "release_date": "2026-08-21",
    "release_type": "ALBUM",
    "total_tracks": 12,
    "trending_rank": 67,
    "popularity_raw": 51,
    "popularity_this_week": "51 pts",
    "genre_category": "POWER POP",
    "badge": "Tendencia Semanal",
    "is_new": false,
    "record_club_url": "https://record.club/releases/albums/weezer-7"
  },
  {
    "id": "5zgrel4dr3glv319",
    "album_name": "Sgt. Pepper’s Lonely Hearts Club Band",
    "artist_name": "The Beatles",
    "image_url": "https://cdn.rcrd.club/releases/5zgrel4dr3glv319/3qe68y9gvp2lrv01.webp?v=29759367493&width=500",
    "release_date": "1967-05-26",
    "release_type": "ALBUM",
    "total_tracks": 12,
    "trending_rank": 68,
    "popularity_raw": 50,
    "popularity_this_week": "50 pts",
    "genre_category": "CLASSIC ROCK",
    "badge": "Tendencia Semanal",
    "is_new": false,
    "record_club_url": "https://record.club/releases/albums/the-beatles-sgt-peppers-lonely-hearts-club-band"
  },
  {
    "id": "nvj0kzx7pvjld3rm",
    "album_name": "IGOR",
    "artist_name": "Tyler, The Creator",
    "image_url": "https://cdn.rcrd.club/releases/nvj0kzx7pvjld3rm/05golqmp55rk1j23.webp?v=23182237048&width=500",
    "release_date": "2019-05-17",
    "release_type": "ALBUM",
    "total_tracks": 12,
    "trending_rank": 69,
    "popularity_raw": 50,
    "popularity_this_week": "50 pts",
    "genre_category": "ALTERNATIVE HIP-HOP",
    "badge": "Tendencia Semanal",
    "is_new": false,
    "record_club_url": "https://record.club/releases/albums/tyler-the-creator-igor"
  },
  {
    "id": "zgrel4r7v1gkv319",
    "album_name": "Daughter from Hell",
    "artist_name": "Gracie Abrams",
    "image_url": "https://cdn.rcrd.club/releases/zgrel4r7v1gkv319/ry7v833qy068x9z0.webp?v=45099519560&width=500",
    "release_date": "2026-07-17",
    "release_type": "ALBUM",
    "total_tracks": 12,
    "trending_rank": 70,
    "popularity_raw": 50,
    "popularity_this_week": "50 pts",
    "genre_category": "BEDROOM POP",
    "badge": "Tendencia Semanal",
    "is_new": false,
    "record_club_url": "https://record.club/releases/albums/gracie-abrams-daughter-from-hell"
  },
  {
    "id": "v9yq8wqdgo58451e",
    "album_name": "Hempispheres",
    "artist_name": "Sleep",
    "image_url": "https://cdn.rcrd.club/releases/v9yq8wqdgo58451e.webp?width=500",
    "release_date": "2026-09-03",
    "release_type": "ALBUM",
    "total_tracks": 12,
    "trending_rank": 71,
    "popularity_raw": 50,
    "popularity_this_week": "50 pts",
    "genre_category": "STONER ROCK",
    "badge": "NEW",
    "is_new": true,
    "record_club_url": "https://record.club/releases/albums/sleep-hempispheres"
  },
  {
    "id": "32j5gkrzn5w81yp4",
    "album_name": "The Beatles",
    "artist_name": "The Beatles",
    "image_url": "https://cdn.rcrd.club/releases/32j5gkrzn5w81yp4/56nvj0kz5vkd3rmz.webp?v=4924862361&width=500",
    "release_date": "1968-11-22",
    "release_type": "ALBUM",
    "total_tracks": 12,
    "trending_rank": 72,
    "popularity_raw": 49,
    "popularity_this_week": "49 pts",
    "genre_category": "CLASSIC ROCK",
    "badge": "Tendencia Semanal",
    "is_new": false,
    "record_club_url": "https://record.club/releases/albums/the-beatles"
  },
  {
    "id": "yz59okeejgqkv6wq",
    "album_name": "The Velvet Underground & Nico",
    "artist_name": "The Velvet Underground & Nico",
    "image_url": "https://cdn.rcrd.club/releases/yz59okeejgqkv6wq/vge38j65p0wln6md.webp?v=13498474967&width=500",
    "release_date": "1967-03-01",
    "release_type": "ALBUM",
    "total_tracks": 12,
    "trending_rank": 73,
    "popularity_raw": 48,
    "popularity_this_week": "48 pts",
    "genre_category": "ART ROCK",
    "badge": "Tendencia Semanal",
    "is_new": false,
    "record_club_url": "https://record.club/releases/albums/the-velvet-underground-nico"
  },
  {
    "id": "zq95kmg3162krvdg",
    "album_name": "Discovery",
    "artist_name": "Daft Punk",
    "image_url": "https://cdn.rcrd.club/releases/zq95kmg3162krvdg/1dezk9gp060lxyq9.webp?v=43702618964&width=500",
    "release_date": "2001-02-26",
    "release_type": "ALBUM",
    "total_tracks": 12,
    "trending_rank": 74,
    "popularity_raw": 48,
    "popularity_this_week": "48 pts",
    "genre_category": "FRENCH HOUSE",
    "badge": "Tendencia Semanal",
    "is_new": false,
    "record_club_url": "https://record.club/releases/albums/daft-punk-discovery"
  },
  {
    "id": "5nm7l0dgwyd8ey69",
    "album_name": "B’Day",
    "artist_name": "Beyoncé",
    "image_url": "https://cdn.rcrd.club/releases/5nm7l0dgwyd8ey69.webp?width=500",
    "release_date": "2006-09-04",
    "release_type": "ALBUM",
    "total_tracks": 12,
    "trending_rank": 75,
    "popularity_raw": 48,
    "popularity_this_week": "48 pts",
    "genre_category": "R&B / POP",
    "badge": "Tendencia Semanal",
    "is_new": false,
    "record_club_url": "https://record.club/releases/albums/beyonce-bday"
  },
  {
    "id": "nvj0kz4x6q48d3rm",
    "album_name": "The Rise and Fall of Ziggy Stardust and the Spiders From Mars",
    "artist_name": "David Bowie",
    "image_url": "https://cdn.rcrd.club/releases/nvj0kz4x6q48d3rm.webp?width=500",
    "release_date": "1972-06-06",
    "release_type": "ALBUM",
    "total_tracks": 12,
    "trending_rank": 76,
    "popularity_raw": 48,
    "popularity_this_week": "48 pts",
    "genre_category": "GLAM ROCK",
    "badge": "Tendencia Semanal",
    "is_new": false,
    "record_club_url": "https://record.club/releases/albums/david-bowie-the-rise-and-fall-of-ziggy-stardust-and-the-spiders-from-mars"
  },
  {
    "id": "ry7v83xe6ry8x9z0",
    "album_name": "Ö",
    "artist_name": "Fcukers",
    "image_url": "https://cdn.rcrd.club/releases/ry7v83xe6ry8x9z0.webp?width=500",
    "release_date": "2026-03-27",
    "release_type": "ALBUM",
    "total_tracks": 12,
    "trending_rank": 77,
    "popularity_raw": 48,
    "popularity_this_week": "48 pts",
    "genre_category": "DANCE-PUNK",
    "badge": "Tendencia Semanal",
    "is_new": false,
    "record_club_url": "https://record.club/releases/albums/fcukers-o"
  },
  {
    "id": "5nm7l0z577zkey69",
    "album_name": "My New Band Believe",
    "artist_name": "My New Band Believe",
    "image_url": "https://cdn.rcrd.club/releases/5nm7l0z577zkey69/z59okewrxr0kv6wq.webp?v=44825117783&width=500",
    "release_date": "2026-04-10",
    "release_type": "ALBUM",
    "total_tracks": 12,
    "trending_rank": 78,
    "popularity_raw": 48,
    "popularity_this_week": "48 pts",
    "genre_category": "INDIE ROCK",
    "badge": "Tendencia Semanal",
    "is_new": false,
    "record_club_url": "https://record.club/releases/albums/my-new-band-believe"
  },
  {
    "id": "5zegl2eg4q1l4ymq",
    "album_name": "Blood of Your Empire",
    "artist_name": "PRESIDENT",
    "image_url": "https://cdn.rcrd.club/releases/5zegl2eg4q1l4ymq.webp?width=500",
    "release_date": "2026-09-04",
    "release_type": "ALBUM",
    "total_tracks": 12,
    "trending_rank": 79,
    "popularity_raw": 48,
    "popularity_this_week": "48 pts",
    "genre_category": "PUNK / ROCK",
    "badge": "NEW",
    "is_new": true,
    "record_club_url": "https://record.club/releases/albums/president-blood-of-your-empire"
  },
  {
    "id": "2j5gkre5zrw81yp4",
    "album_name": "ᲘᲘ",
    "artist_name": "Cyst",
    "image_url": "https://cdn.rcrd.club/releases/2j5gkre5zrw81yp4.webp?width=500",
    "release_date": "2026-09-04",
    "release_type": "ALBUM",
    "total_tracks": 12,
    "trending_rank": 80,
    "popularity_raw": 48,
    "popularity_this_week": "48 pts",
    "genre_category": "EXPERIMENTAL",
    "badge": "NEW",
    "is_new": true,
    "record_club_url": "https://record.club/releases/albums/cyst-r-09a3017895"
  },
  {
    "id": "3qe68y07v6olrv01",
    "album_name": "Czarface Meets Frankie Pulitzer",
    "artist_name": "Czarface & Frankie Pulitzer",
    "image_url": "https://cdn.rcrd.club/releases/3qe68y07v6olrv01.webp?width=500",
    "release_date": "2026-08-28",
    "release_type": "ALBUM",
    "total_tracks": 12,
    "trending_rank": 81,
    "popularity_raw": 48,
    "popularity_this_week": "48 pts",
    "genre_category": "BOOM BAP HIP-HOP",
    "badge": "Tendencia Semanal",
    "is_new": false,
    "record_club_url": "https://record.club/releases/albums/czarface-frankie-pulitzer-czarface-meets-frankie-pulitzer"
  },
  {
    "id": "ry7v83g290vkx9z0",
    "album_name": "BRAT",
    "artist_name": "Charli xcx",
    "image_url": "https://cdn.rcrd.club/releases/ry7v83g290vkx9z0/0592lpdj99xl41r6.webp?v=44951744950&width=500",
    "release_date": "2024-06-07",
    "release_type": "ALBUM",
    "total_tracks": 12,
    "trending_rank": 82,
    "popularity_raw": 47,
    "popularity_this_week": "47 pts",
    "genre_category": "HYPERPOP / CLUB",
    "badge": "Tendencia Semanal",
    "is_new": false,
    "record_club_url": "https://record.club/releases/albums/charli-xcx-brat"
  },
  {
    "id": "ry7v83xezev8x9z0",
    "album_name": "My Ghosts Go Ghost",
    "artist_name": "By Storm",
    "image_url": "https://cdn.rcrd.club/releases/ry7v83xezev8x9z0/ry7v830vdwj8x9z0.webp?v=44226441401&width=500",
    "release_date": "2026-01-30",
    "release_type": "ALBUM",
    "total_tracks": 12,
    "trending_rank": 83,
    "popularity_raw": 47,
    "popularity_this_week": "47 pts",
    "genre_category": "ALTERNATIVE HIP-HOP",
    "badge": "Tendencia Semanal",
    "is_new": false,
    "record_club_url": "https://record.club/releases/albums/by-storm-my-ghosts-go-ghost"
  },
  {
    "id": "5zegl264gz184ymq",
    "album_name": "Superbloom",
    "artist_name": "Jessie Ware",
    "image_url": "https://cdn.rcrd.club/releases/5zegl264gz184ymq/ox4n875xr7zkdpez.webp?v=44892160270&width=500",
    "release_date": "2026-04-17",
    "release_type": "ALBUM",
    "total_tracks": 12,
    "trending_rank": 84,
    "popularity_raw": 47,
    "popularity_this_week": "47 pts",
    "genre_category": "DISCO / DANCE-POP",
    "badge": "Tendencia Semanal",
    "is_new": false,
    "record_club_url": "https://record.club/releases/albums/jessie-ware-superbloom"
  }
];

export const CURATED_ANTICIPATED_RELEASES = [
  {
    "id": "ant_blossoms_2026",
    "album_name": "Songs from the Wedding Cake",
    "artist_name": "Blossoms",
    "image_url": "https://cdn-images.dzcdn.net/images/cover/e8c55456e7f24da86601ebd4d96067aa/1000x1000-000000-80-0-0.jpg",
    "release_date": "2026-10-02",
    "release_type": "ALBUM",
    "status": "ANTICIPADO",
    "genre": "Indie Pop / Rock",
    "description": "Nuevo álbum de estudio de la aclamada banda británica grabado en Stockport y Manchester.",
    "expected_tracks": 12
  },
  {
    "id": "ant_johnny_marr_2026",
    "album_name": "The Age Of Everything",
    "artist_name": "Johnny Marr",
    "image_url": "https://cdn-images.dzcdn.net/images/artist/318e533e6129c1c6eb838e0f823/1000x1000-000000-80-0-0.jpg",
    "release_date": "2026-10-02",
    "release_type": "ALBUM",
    "status": "ANTICIPADO",
    "genre": "Alternative Rock / Post-Punk",
    "description": "El legendario cofundador y guitarrista de The Smiths presenta su nuevo trabajo solista.",
    "expected_tracks": 10
  },
  {
    "id": "ant_troye_sivan_2026",
    "album_name": "She’s the Best",
    "artist_name": "Troye Sivan",
    "image_url": "https://cdn-images.dzcdn.net/images/artist/968460c08486bc17aafc1d4398e/1000x1000-000000-80-0-0.jpg",
    "release_date": "2026-10-09",
    "release_type": "ALBUM",
    "status": "ANTICIPADO",
    "genre": "Dance-Pop / Synthpop",
    "description": "El esperado siguiente LP tras el fenómeno global de Something to Give Each Other y Rush.",
    "expected_tracks": 11
  },
  {
    "id": "ant_greta_van_fleet_2026",
    "album_name": "Palace for the People",
    "artist_name": "Greta Van Fleet",
    "image_url": "https://cdn-images.dzcdn.net/images/artist/06db73a10aa714ae6a0ed2787d0/1000x1000-000000-80-0-0.jpg",
    "release_date": "2026-10-09",
    "release_type": "ALBUM",
    "status": "ANTICIPADO",
    "genre": "Hard Rock / Classic Rock",
    "description": "Nuevo despliegue de guitarras abrasadoras y virtuosismo vocal por los hermanos Kiszka.",
    "expected_tracks": 11
  },
  {
    "id": "ant_fontaines_dc_2026",
    "album_name": "Dopamine Chamber",
    "artist_name": "Fontaines D.C.",
    "image_url": "https://cdn-images.dzcdn.net/images/cover/8fd422a840884ba1dfaccc3bb42ad67d/1000x1000-000000-80-0-0.jpg",
    "release_date": "2026-10-16",
    "release_type": "ALBUM",
    "status": "ANTICIPADO",
    "genre": "Post-Punk / Alternative",
    "description": "Nuevo proyecto de estudio de la banda irlandesa tras la masiva aclamación crítica de Romance.",
    "expected_tracks": 11
  },
  {
    "id": "ant_cordae_paak_2026",
    "album_name": "Heavy is The Crown",
    "artist_name": "Cordae & Anderson .Paak",
    "image_url": "https://cdn-images.dzcdn.net/images/cover/00dd0da365a94b1829/1000x1000-000000-80-0-0.jpg",
    "release_date": "2026-10-23",
    "release_type": "ALBUM",
    "status": "ANTICIPADO",
    "genre": "Hip-Hop / Neo-Soul",
    "description": "Álbum colaborativo completo entre dos de las voces más creativas del rap y soul contemporáneo.",
    "expected_tracks": 14
  },
  {
    "id": "ant_la_roux_2026",
    "album_name": "Old Flames",
    "artist_name": "La Roux",
    "image_url": "https://cdn-images.dzcdn.net/images/cover/91f8ab3d5dace0f93a4de460a9c5c10b/1000x1000-000000-80-0-0.jpg",
    "release_date": "2026-11-06",
    "release_type": "ALBUM",
    "status": "ANTICIPADO",
    "genre": "Synthpop / Electro-Pop",
    "description": "El regreso de Elly Jackson con sintetizadores analógicos y grooves bailables electrizantes.",
    "expected_tracks": 10
  },
  {
    "id": "ant_royal_blood_2026",
    "album_name": "Dead Company",
    "artist_name": "Royal Blood",
    "image_url": "https://cdn-images.dzcdn.net/images/artist/dd47ec0db2813508d1a7a14fbe1/1000x1000-000000-80-0-0.jpg",
    "release_date": "2026-11-13",
    "release_type": "ALBUM",
    "status": "ANTICIPADO",
    "genre": "Hard Rock / Alternative",
    "description": "El nuevo arsenal de riffs distorsionados y potencia rítmica del poderoso dúo británico.",
    "expected_tracks": 10
  },
  {
    "id": "ant_lana_del_rey_2026",
    "album_name": "Stove",
    "artist_name": "Lana Del Rey",
    "image_url": "https://cdn-images.dzcdn.net/images/cover/c0f4f022fa51f13e877aae2e758e241d/1000x1000-000000-80-0-0.jpg",
    "release_date": "2026-11-27",
    "release_type": "ALBUM",
    "status": "ANTICIPADO",
    "genre": "Americana / Country Pop",
    "description": "El esperado álbum con sonido acústico y raíces sureñas anunciado por Lana Del Rey con Jack Antonoff y Luke Laird.",
    "expected_tracks": 13
  }
];

export const RECORD_CLUB_FALLBACK_UPCOMING = [
  {
    "id": "5wyz8dv1xzz8xve9",
    "album_name": "Day and Night",
    "artist_name": "Carly Rae Jepsen",
    "image_url": "https://cdn.rcrd.club/releases/5wyz8dv1xzz8xve9.webp?width=500",
    "release_date": "2026-09-18",
    "release_type": "ALBUM",
    "total_tracks": 10,
    "popularity_rank": 1,
    "popularity_raw": 327,
    "genre": "POP / ALTERNATIVE",
    "description": "Lanzamiento anunciado oficialmente.",
    "record_club_url": "https://record.club/releases/albums/carly-rae-jepsen-day-and-night"
  },
  {
    "id": "1dezk9w727w8xyq9",
    "album_name": "Pylon",
    "artist_name": "beabadoobee",
    "image_url": "https://cdn.rcrd.club/releases/1dezk9w727w8xyq9.webp?width=500",
    "release_date": "2026-09-18",
    "release_type": "ALBUM",
    "total_tracks": 10,
    "popularity_rank": 2,
    "popularity_raw": 286,
    "genre": "POP / ALTERNATIVE",
    "description": "Lanzamiento anunciado oficialmente.",
    "record_club_url": "https://record.club/releases/albums/beabadoobee-pylon"
  },
  {
    "id": "v9yq8wqj92g8451e",
    "album_name": "Dopamine Chamber",
    "artist_name": "FONTAINES D.C.",
    "image_url": "https://cdn.rcrd.club/releases/v9yq8wqj92g8451e/yze2k1v623yk40wq.webp?v=45951664105&width=500",
    "release_date": "2026-10-16",
    "release_type": "ALBUM",
    "total_tracks": 10,
    "popularity_rank": 3,
    "popularity_raw": 178,
    "genre": "POP / ALTERNATIVE",
    "description": "Lanzamiento anunciado oficialmente.",
    "record_club_url": "https://record.club/releases/albums/fontaines-dc-dopamine-chamber"
  },
  {
    "id": "z59oke9ooqqlv6wq",
    "album_name": "Popstar",
    "artist_name": "Tinashe",
    "image_url": "https://cdn.rcrd.club/releases/z59oke9ooqqlv6wq.webp?width=500",
    "release_date": "2026-09-25",
    "release_type": "ALBUM",
    "total_tracks": 10,
    "popularity_rank": 4,
    "popularity_raw": 175,
    "genre": "POP / ALTERNATIVE",
    "description": "Lanzamiento anunciado oficialmente.",
    "record_club_url": "https://record.club/releases/albums/tinashe-popstar"
  },
  {
    "id": "ry7v83wgzmjlx9z0",
    "album_name": "ESTRUS",
    "artist_name": "Tove Lo",
    "image_url": "https://cdn.rcrd.club/releases/ry7v83wgzmjlx9z0/5zegl2vynmyk4ymq.webp?v=45100008407&width=500",
    "release_date": "2026-09-18",
    "release_type": "ALBUM",
    "total_tracks": 10,
    "popularity_rank": 5,
    "popularity_raw": 120,
    "genre": "POP / ALTERNATIVE",
    "description": "Lanzamiento anunciado oficialmente.",
    "record_club_url": "https://record.club/releases/albums/tove-lo-estrus"
  },
  {
    "id": "vge38jd4mmm8n6md",
    "album_name": "She’s the Best",
    "artist_name": "Troye Sivan",
    "image_url": "https://cdn.rcrd.club/releases/vge38jd4mmm8n6md.webp?width=500",
    "release_date": "2026-10-09",
    "release_type": "ALBUM",
    "total_tracks": 10,
    "popularity_rank": 6,
    "popularity_raw": 112,
    "genre": "POP / ALTERNATIVE",
    "description": "Lanzamiento anunciado oficialmente.",
    "record_club_url": "https://record.club/releases/albums/troye-sivan-shes-the-best"
  },
  {
    "id": "v9yq8wqxx9y8451e",
    "album_name": "Angel",
    "artist_name": "Lizzy McAlpine",
    "image_url": "https://cdn.rcrd.club/releases/v9yq8wqxx9y8451e.webp?width=500",
    "release_date": "2026-09-18",
    "release_type": "ALBUM",
    "total_tracks": 10,
    "popularity_rank": 7,
    "popularity_raw": 94,
    "genre": "POP / ALTERNATIVE",
    "description": "Lanzamiento anunciado oficialmente.",
    "record_club_url": "https://record.club/releases/albums/lizzy-mcalpine-angel"
  },
  {
    "id": "zgrel4rq3p4kv319",
    "album_name": "I think I spoke too soon",
    "artist_name": "Rachel Chinouriri",
    "image_url": "https://cdn.rcrd.club/releases/zgrel4rq3p4kv319.webp?width=500",
    "release_date": "2026-10-16",
    "release_type": "ALBUM",
    "total_tracks": 10,
    "popularity_rank": 8,
    "popularity_raw": 76,
    "genre": "POP / ALTERNATIVE",
    "description": "Lanzamiento anunciado oficialmente.",
    "record_club_url": "https://record.club/releases/albums/rachel-chinouriri-i-think-i-spoke-too-soon"
  },
  {
    "id": "z59oke9yjdplv6wq",
    "album_name": "No Bad Memories",
    "artist_name": "The Avalanches",
    "image_url": "https://cdn.rcrd.club/releases/z59oke9yjdplv6wq.webp?width=500",
    "release_date": "2026-10-16",
    "release_type": "ALBUM",
    "total_tracks": 10,
    "popularity_rank": 9,
    "popularity_raw": 70,
    "genre": "POP / ALTERNATIVE",
    "description": "Lanzamiento anunciado oficialmente.",
    "record_club_url": "https://record.club/releases/albums/the-avalanches-no-bad-memories"
  },
  {
    "id": "932185ww64x8po7m",
    "album_name": "Melodie",
    "artist_name": "Slow Pulp",
    "image_url": "https://cdn.rcrd.club/releases/932185ww64x8po7m/5zegl2v2g41k4ymq.webp?v=45358171742&width=500",
    "release_date": "2026-09-18",
    "release_type": "ALBUM",
    "total_tracks": 10,
    "popularity_rank": 10,
    "popularity_raw": 52,
    "genre": "POP / ALTERNATIVE",
    "description": "Lanzamiento anunciado oficialmente.",
    "record_club_url": "https://record.club/releases/albums/slow-pulp-melodie"
  },
  {
    "id": "1dezk9qmrqw8xyq9",
    "album_name": "Perfecth",
    "artist_name": "Queens of the Stone Age",
    "image_url": "https://cdn.rcrd.club/releases/1dezk9qmrqw8xyq9.webp?width=500",
    "release_date": "2026-10-30",
    "release_type": "ALBUM",
    "total_tracks": 10,
    "popularity_rank": 11,
    "popularity_raw": 49,
    "genre": "POP / ALTERNATIVE",
    "description": "Lanzamiento anunciado oficialmente.",
    "record_club_url": "https://record.club/releases/albums/queens-of-the-stone-age-perfecth"
  },
  {
    "id": "mv6nkn1wy5n8qxod",
    "album_name": "Bass Persuades",
    "artist_name": "MILEY",
    "image_url": "https://cdn.rcrd.club/releases/mv6nkn1wy5n8qxod.webp?width=500",
    "release_date": "2026-09-18",
    "release_type": "ALBUM",
    "total_tracks": 10,
    "popularity_rank": 12,
    "popularity_raw": 49,
    "genre": "POP / ALTERNATIVE",
    "description": "Lanzamiento anunciado oficialmente.",
    "record_club_url": "https://record.club/releases/albums/miley-bass-persuades"
  },
  {
    "id": "932185ww1no8po7m",
    "album_name": "The Gem",
    "artist_name": "Julia Jacklin",
    "image_url": "https://cdn.rcrd.club/releases/932185ww1no8po7m.webp?width=500",
    "release_date": "2026-09-25",
    "release_type": "ALBUM",
    "total_tracks": 10,
    "popularity_rank": 13,
    "popularity_raw": 46,
    "genre": "POP / ALTERNATIVE",
    "description": "Lanzamiento anunciado oficialmente.",
    "record_club_url": "https://record.club/releases/albums/julia-jacklin-the-gem"
  },
  {
    "id": "2j5gkred7p381yp4",
    "album_name": "These Killing Times",
    "artist_name": "Emma Ruth Rundle",
    "image_url": "https://cdn.rcrd.club/releases/2j5gkred7p381yp4.webp?width=500",
    "release_date": "2026-09-18",
    "release_type": "ALBUM",
    "total_tracks": 10,
    "popularity_rank": 14,
    "popularity_raw": 42,
    "genre": "POP / ALTERNATIVE",
    "description": "Lanzamiento anunciado oficialmente.",
    "record_club_url": "https://record.club/releases/albums/emma-ruth-rundle-these-killing-times"
  },
  {
    "id": "2j5gkrej33181yp4",
    "album_name": "Ride Lonesome",
    "artist_name": "Beck",
    "image_url": "https://cdn.rcrd.club/releases/2j5gkrej33181yp4.webp?width=500",
    "release_date": "2026-09-18",
    "release_type": "ALBUM",
    "total_tracks": 10,
    "popularity_rank": 15,
    "popularity_raw": 42,
    "genre": "POP / ALTERNATIVE",
    "description": "Lanzamiento anunciado oficialmente.",
    "record_club_url": "https://record.club/releases/albums/beck-ride-lonesome-2"
  },
  {
    "id": "zq95kme2j3mlrvdg",
    "album_name": "Violins",
    "artist_name": "Blondshell",
    "image_url": "https://cdn.rcrd.club/releases/zq95kme2j3mlrvdg.webp?width=500",
    "release_date": "2026-09-25",
    "release_type": "ALBUM",
    "total_tracks": 10,
    "popularity_rank": 16,
    "popularity_raw": 39,
    "genre": "POP / ALTERNATIVE",
    "description": "Lanzamiento anunciado oficialmente.",
    "record_club_url": "https://record.club/releases/albums/blondshell-violins"
  },
  {
    "id": "3qe68y0gg62lrv01",
    "album_name": "I Wrote You a Letter",
    "artist_name": "M83",
    "image_url": "https://cdn.rcrd.club/releases/3qe68y0gg62lrv01.webp?width=500",
    "release_date": "2026-09-25",
    "release_type": "ALBUM",
    "total_tracks": 10,
    "popularity_rank": 17,
    "popularity_raw": 38,
    "genre": "POP / ALTERNATIVE",
    "description": "Lanzamiento anunciado oficialmente.",
    "record_club_url": "https://record.club/releases/albums/m83-i-wrote-you-a-letter"
  },
  {
    "id": "5zegl2e1m0dl4ymq",
    "album_name": "Happiness Anytime",
    "artist_name": "Leon Bridges",
    "image_url": "https://cdn.rcrd.club/releases/5zegl2e1m0dl4ymq/01d4kvwmngel76m2.webp?v=45680572932&width=500",
    "release_date": "2026-09-25",
    "release_type": "ALBUM",
    "total_tracks": 10,
    "popularity_rank": 18,
    "popularity_raw": 36,
    "genre": "POP / ALTERNATIVE",
    "description": "Lanzamiento anunciado oficialmente.",
    "record_club_url": "https://record.club/releases/albums/leon-bridges-happiness-anytime"
  },
  {
    "id": "3qe68y0ggnwlrv01",
    "album_name": "Frequency of Love",
    "artist_name": "Victoria Monét",
    "image_url": "https://cdn.rcrd.club/releases/3qe68y0ggnwlrv01.webp?width=500",
    "release_date": "2026-10-02",
    "release_type": "ALBUM",
    "total_tracks": 10,
    "popularity_rank": 19,
    "popularity_raw": 36,
    "genre": "POP / ALTERNATIVE",
    "description": "Lanzamiento anunciado oficialmente.",
    "record_club_url": "https://record.club/releases/albums/victoria-monet-frequency-of-love"
  },
  {
    "id": "mv6nknroqjglqxod",
    "album_name": "Mud",
    "artist_name": "Remi Wolf",
    "image_url": "https://cdn.rcrd.club/releases/mv6nknroqjglqxod.webp?width=500",
    "release_date": "2026-10-09",
    "release_type": "ALBUM",
    "total_tracks": 10,
    "popularity_rank": 20,
    "popularity_raw": 35,
    "genre": "POP / ALTERNATIVE",
    "description": "Lanzamiento anunciado oficialmente.",
    "record_club_url": "https://record.club/releases/albums/remi-wolf-mud"
  },
  {
    "id": "5zegl2e1nj1l4ymq",
    "album_name": "Newly Sentient Being",
    "artist_name": "Swans",
    "image_url": "https://cdn.rcrd.club/releases/5zegl2e1nj1l4ymq.webp?width=500",
    "release_date": "2026-10-02",
    "release_type": "ALBUM",
    "total_tracks": 10,
    "popularity_rank": 21,
    "popularity_raw": 34,
    "genre": "POP / ALTERNATIVE",
    "description": "Lanzamiento anunciado oficialmente.",
    "record_club_url": "https://record.club/releases/albums/swans-newly-sentient-being"
  },
  {
    "id": "5zegl2ew91jl4ymq",
    "album_name": "Fell Asleep in the Sun",
    "artist_name": "After",
    "image_url": "https://cdn.rcrd.club/releases/5zegl2ew91jl4ymq.webp?width=500",
    "release_date": "2026-09-18",
    "release_type": "ALBUM",
    "total_tracks": 10,
    "popularity_rank": 22,
    "popularity_raw": 32,
    "genre": "POP / ALTERNATIVE",
    "description": "Lanzamiento anunciado oficialmente.",
    "record_club_url": "https://record.club/releases/albums/after-fell-asleep-in-the-sun"
  },
  {
    "id": "0592lpz47v9841r6",
    "album_name": "Stray Dogs",
    "artist_name": "Nothing But Thieves",
    "image_url": "https://cdn.rcrd.club/releases/0592lpz47v9841r6.webp?width=500",
    "release_date": "2026-09-25",
    "release_type": "ALBUM",
    "total_tracks": 10,
    "popularity_rank": 23,
    "popularity_raw": 31,
    "genre": "POP / ALTERNATIVE",
    "description": "Lanzamiento anunciado oficialmente.",
    "record_club_url": "https://record.club/releases/albums/nothing-but-thieves-stray-dogs"
  },
  {
    "id": "zgrel4rw3w2kv319",
    "album_name": "ZIRP!",
    "artist_name": "DIIV",
    "image_url": "https://cdn.rcrd.club/releases/zgrel4rw3w2kv319.webp?width=500",
    "release_date": "2026-10-30",
    "release_type": "ALBUM",
    "total_tracks": 10,
    "popularity_rank": 24,
    "popularity_raw": 31,
    "genre": "POP / ALTERNATIVE",
    "description": "Lanzamiento anunciado oficialmente.",
    "record_club_url": "https://record.club/releases/albums/diiv-zirp"
  },
  {
    "id": "nvj0kz6pwnvld3rm",
    "album_name": "Hotel Usona",
    "artist_name": "Protomartyr",
    "image_url": "https://cdn.rcrd.club/releases/nvj0kz6pwnvld3rm.webp?width=500",
    "release_date": "2026-09-25",
    "release_type": "ALBUM",
    "total_tracks": 10,
    "popularity_rank": 25,
    "popularity_raw": 29,
    "genre": "POP / ALTERNATIVE",
    "description": "Lanzamiento anunciado oficialmente.",
    "record_club_url": "https://record.club/releases/albums/protomartyr-hotel-usona"
  },
  {
    "id": "ry7v83w196ylx9z0",
    "album_name": "GET MEAN",
    "artist_name": "Boy Harsher",
    "image_url": "https://cdn.rcrd.club/releases/ry7v83w196ylx9z0.webp?width=500",
    "release_date": "2026-09-18",
    "release_type": "ALBUM",
    "total_tracks": 10,
    "popularity_rank": 26,
    "popularity_raw": 26,
    "genre": "POP / ALTERNATIVE",
    "description": "Lanzamiento anunciado oficialmente.",
    "record_club_url": "https://record.club/releases/albums/boy-harsher-get-mean"
  },
  {
    "id": "5wyz8dv64n08xve9",
    "album_name": "Dream House",
    "artist_name": "Empress Of",
    "image_url": "https://cdn.rcrd.club/releases/5wyz8dv64n08xve9.webp?width=500",
    "release_date": "2026-09-18",
    "release_type": "ALBUM",
    "total_tracks": 10,
    "popularity_rank": 27,
    "popularity_raw": 25,
    "genre": "POP / ALTERNATIVE",
    "description": "Lanzamiento anunciado oficialmente.",
    "record_club_url": "https://record.club/releases/albums/empress-of-dream-house-2"
  },
  {
    "id": "ox4n879g341ldpez",
    "album_name": "Cancel Me (I'm Tired)",
    "artist_name": "Fat Dog",
    "image_url": "https://cdn.rcrd.club/releases/ox4n879g341ldpez.webp?width=500",
    "release_date": "2026-10-02",
    "release_type": "ALBUM",
    "total_tracks": 10,
    "popularity_rank": 28,
    "popularity_raw": 24,
    "genre": "POP / ALTERNATIVE",
    "description": "Lanzamiento anunciado oficialmente.",
    "record_club_url": "https://record.club/releases/albums/fat-dog-cancel-me-im-tired-2"
  },
  {
    "id": "2j5gkre29jy81yp4",
    "album_name": "AUDACITY",
    "artist_name": "Jae Stephens",
    "image_url": "https://cdn.rcrd.club/releases/2j5gkre29jy81yp4.webp?width=500",
    "release_date": "2026-09-25",
    "release_type": "ALBUM",
    "total_tracks": 10,
    "popularity_rank": 29,
    "popularity_raw": 24,
    "genre": "POP / ALTERNATIVE",
    "description": "Lanzamiento anunciado oficialmente.",
    "record_club_url": "https://record.club/releases/albums/jae-stephens-audacity"
  },
  {
    "id": "05golqey6xml1j23",
    "album_name": "Old Flames",
    "artist_name": "La Roux",
    "image_url": "https://cdn.rcrd.club/releases/05golqey6xml1j23/mv6nknjnze58qxod.webp?v=45236677329&width=500",
    "release_date": "2026-11-06",
    "release_type": "ALBUM",
    "total_tracks": 10,
    "popularity_rank": 30,
    "popularity_raw": 23,
    "genre": "POP / ALTERNATIVE",
    "description": "Lanzamiento anunciado oficialmente.",
    "record_club_url": "https://record.club/releases/albums/la-roux-old-flames"
  },
  {
    "id": "5nm7l0w15vdkey69",
    "album_name": "Do Not Dare To Dream",
    "artist_name": "Teenage Fanclub",
    "image_url": "https://cdn.rcrd.club/releases/5nm7l0w15vdkey69.webp?width=500",
    "release_date": "2026-10-09",
    "release_type": "ALBUM",
    "total_tracks": 10,
    "popularity_rank": 31,
    "popularity_raw": 23,
    "genre": "POP / ALTERNATIVE",
    "description": "Lanzamiento anunciado oficialmente.",
    "record_club_url": "https://record.club/releases/albums/teenage-fanclub-do-not-dare-to-dream"
  },
  {
    "id": "r5eokoe23jd861n4",
    "album_name": "Live at Carnegie Hall",
    "artist_name": "Cameron Winter",
    "image_url": "https://cdn.rcrd.club/releases/r5eokoe23jd861n4.webp?width=500",
    "release_date": "2026-10-09",
    "release_type": "ALBUM",
    "total_tracks": 10,
    "popularity_rank": 32,
    "popularity_raw": 23,
    "genre": "POP / ALTERNATIVE",
    "description": "Lanzamiento anunciado oficialmente.",
    "record_club_url": "https://record.club/releases/albums/cameron-winter-live-at-carnegie-hall"
  },
  {
    "id": "5zegl2eg3ejl4ymq",
    "album_name": "Cursum Perficio",
    "artist_name": "Anthrax",
    "image_url": "https://cdn.rcrd.club/releases/5zegl2eg3ejl4ymq.webp?width=500",
    "release_date": "2026-09-18",
    "release_type": "ALBUM",
    "total_tracks": 10,
    "popularity_rank": 33,
    "popularity_raw": 20,
    "genre": "POP / ALTERNATIVE",
    "description": "Lanzamiento anunciado oficialmente.",
    "record_club_url": "https://record.club/releases/albums/anthrax-cursum-perficio"
  },
  {
    "id": "0592lpz44jx841r6",
    "album_name": "Solaris",
    "artist_name": "The Ocean",
    "image_url": "https://cdn.rcrd.club/releases/0592lpz44jx841r6.webp?width=500",
    "release_date": "2026-09-25",
    "release_type": "ALBUM",
    "total_tracks": 10,
    "popularity_rank": 34,
    "popularity_raw": 20,
    "genre": "POP / ALTERNATIVE",
    "description": "Lanzamiento anunciado oficialmente.",
    "record_club_url": "https://record.club/releases/albums/the-ocean-solaris"
  },
  {
    "id": "ox4n879qz0xldpez",
    "album_name": "Tough Love",
    "artist_name": "Nessa Barrett",
    "image_url": "https://cdn.rcrd.club/releases/ox4n879qz0xldpez.webp?width=500",
    "release_date": "2026-09-25",
    "release_type": "ALBUM",
    "total_tracks": 10,
    "popularity_rank": 35,
    "popularity_raw": 20,
    "genre": "POP / ALTERNATIVE",
    "description": "Lanzamiento anunciado oficialmente.",
    "record_club_url": "https://record.club/releases/albums/nessa-barrett-tough-love"
  },
  {
    "id": "2gpqkx5zwgj83r45",
    "album_name": "Autosmile",
    "artist_name": "@",
    "image_url": "https://cdn.rcrd.club/releases/2gpqkx5zwgj83r45.webp?width=500",
    "release_date": "2026-10-16",
    "release_type": "ALBUM",
    "total_tracks": 10,
    "popularity_rank": 36,
    "popularity_raw": 19,
    "genre": "POP / ALTERNATIVE",
    "description": "Lanzamiento anunciado oficialmente.",
    "record_club_url": "https://record.club/releases/albums/r-e005826fcb-autosmile"
  },
  {
    "id": "r5eokoeejp7861n4",
    "album_name": "Nature’s Pill",
    "artist_name": "Wishy",
    "image_url": "https://cdn.rcrd.club/releases/r5eokoeejp7861n4.webp?width=500",
    "release_date": "2026-10-02",
    "release_type": "ALBUM",
    "total_tracks": 10,
    "popularity_rank": 37,
    "popularity_raw": 18,
    "genre": "POP / ALTERNATIVE",
    "description": "Lanzamiento anunciado oficialmente.",
    "record_club_url": "https://record.club/releases/albums/wishy-natures-pill"
  },
  {
    "id": "3wxr86zq3rdl2gny",
    "album_name": "Pugnello",
    "artist_name": "Gilla Band",
    "image_url": "https://cdn.rcrd.club/releases/3wxr86zq3rdl2gny.webp?width=500",
    "release_date": "2026-09-25",
    "release_type": "ALBUM",
    "total_tracks": 10,
    "popularity_rank": 38,
    "popularity_raw": 18,
    "genre": "POP / ALTERNATIVE",
    "description": "Lanzamiento anunciado oficialmente.",
    "record_club_url": "https://record.club/releases/albums/gilla-band-pugnello"
  },
  {
    "id": "zgrel4r31z2kv319",
    "album_name": "In Endless Awe & Agony",
    "artist_name": "daine",
    "image_url": "https://cdn.rcrd.club/releases/zgrel4r31z2kv319.webp?width=500",
    "release_date": "2026-11-06",
    "release_type": "ALBUM",
    "total_tracks": 10,
    "popularity_rank": 39,
    "popularity_raw": 18,
    "genre": "POP / ALTERNATIVE",
    "description": "Lanzamiento anunciado oficialmente.",
    "record_club_url": "https://record.club/releases/albums/daine-in-endless-awe-agony"
  },
  {
    "id": "vge38jdo17e8n6md",
    "album_name": "All Set the Bone",
    "artist_name": "Greg Freeman",
    "image_url": "https://cdn.rcrd.club/releases/vge38jdo17e8n6md.webp?width=500",
    "release_date": "2026-10-02",
    "release_type": "ALBUM",
    "total_tracks": 10,
    "popularity_rank": 40,
    "popularity_raw": 18,
    "genre": "POP / ALTERNATIVE",
    "description": "Lanzamiento anunciado oficialmente.",
    "record_club_url": "https://record.club/releases/albums/greg-freeman-all-set-the-bone"
  },
  {
    "id": "0592lpz63w6841r6",
    "album_name": "Apples for Isaac",
    "artist_name": "Echo & the Bunnymen",
    "image_url": "https://cdn.rcrd.club/releases/0592lpz63w6841r6.webp?width=500",
    "release_date": "2026-09-18",
    "release_type": "ALBUM",
    "total_tracks": 10,
    "popularity_rank": 41,
    "popularity_raw": 17,
    "genre": "POP / ALTERNATIVE",
    "description": "Lanzamiento anunciado oficialmente.",
    "record_club_url": "https://record.club/releases/albums/echo-the-bunnymen-apples-for-isaac"
  },
  {
    "id": "5zegl2eg9pjl4ymq",
    "album_name": "Nobody's Coming to Save You",
    "artist_name": "Gurriers",
    "image_url": "https://cdn.rcrd.club/releases/5zegl2eg9pjl4ymq.webp?width=500",
    "release_date": "2026-09-25",
    "release_type": "ALBUM",
    "total_tracks": 10,
    "popularity_rank": 42,
    "popularity_raw": 16,
    "genre": "POP / ALTERNATIVE",
    "description": "Lanzamiento anunciado oficialmente.",
    "record_club_url": "https://record.club/releases/albums/gurriers-nobodys-coming-to-save-you"
  },
  {
    "id": "z59oke9x7pylv6wq",
    "album_name": "In the Shadow of Your Shadow",
    "artist_name": "Cult of Luna",
    "image_url": "https://cdn.rcrd.club/releases/z59oke9x7pylv6wq.webp?width=500",
    "release_date": "2026-11-06",
    "release_type": "ALBUM",
    "total_tracks": 10,
    "popularity_rank": 43,
    "popularity_raw": 16,
    "genre": "POP / ALTERNATIVE",
    "description": "Lanzamiento anunciado oficialmente.",
    "record_club_url": "https://record.club/releases/albums/cult-of-luna-in-the-shadow-of-your-shadow-2"
  },
  {
    "id": "5wyz8dvxmzr8xve9",
    "album_name": "A Safe Place To Be Wild",
    "artist_name": "Jordan Rakei",
    "image_url": "https://cdn.rcrd.club/releases/5wyz8dvxmzr8xve9.webp?width=500",
    "release_date": "2026-10-30",
    "release_type": "ALBUM",
    "total_tracks": 10,
    "popularity_rank": 44,
    "popularity_raw": 16,
    "genre": "POP / ALTERNATIVE",
    "description": "Lanzamiento anunciado oficialmente.",
    "record_club_url": "https://record.club/releases/albums/jordan-rakei-a-safe-place-to-be-wild"
  },
  {
    "id": "yze2k1971z0840wq",
    "album_name": "How To Quit Smoking",
    "artist_name": "Dominic Fike",
    "image_url": "https://cdn.rcrd.club/releases/yze2k1971z0840wq.webp?width=500",
    "release_date": "2026-10-09",
    "release_type": "ALBUM",
    "total_tracks": 10,
    "popularity_rank": 45,
    "popularity_raw": 16,
    "genre": "POP / ALTERNATIVE",
    "description": "Lanzamiento anunciado oficialmente.",
    "record_club_url": "https://record.club/releases/albums/dominic-fike-how-to-quit-smoking"
  },
  {
    "id": "1dezk9w60w08xyq9",
    "album_name": "Lucro Sucio; Unfinished Business",
    "artist_name": "The Mars Volta",
    "image_url": "https://cdn.rcrd.club/releases/1dezk9w60w08xyq9.webp?width=500",
    "release_date": "2026-10-16",
    "release_type": "ALBUM",
    "total_tracks": 10,
    "popularity_rank": 46,
    "popularity_raw": 15,
    "genre": "POP / ALTERNATIVE",
    "description": "Lanzamiento anunciado oficialmente.",
    "record_club_url": "https://record.club/releases/albums/the-mars-volta-lucro-sucio-unfinished-business"
  },
  {
    "id": "0592lpzoyv9841r6",
    "album_name": "jg",
    "artist_name": "Jacques Greene",
    "image_url": "https://cdn.rcrd.club/releases/0592lpzoyv9841r6.webp?width=500",
    "release_date": "2026-10-16",
    "release_type": "ALBUM",
    "total_tracks": 10,
    "popularity_rank": 47,
    "popularity_raw": 15,
    "genre": "POP / ALTERNATIVE",
    "description": "Lanzamiento anunciado oficialmente.",
    "record_club_url": "https://record.club/releases/albums/jacques-greene-jg"
  },
  {
    "id": "0592lpze64r841r6",
    "album_name": "The Meaning of Flowers",
    "artist_name": "Agnes Obel",
    "image_url": "https://cdn.rcrd.club/releases/0592lpze64r841r6.webp?width=500",
    "release_date": "2026-09-18",
    "release_type": "ALBUM",
    "total_tracks": 10,
    "popularity_rank": 48,
    "popularity_raw": 15,
    "genre": "POP / ALTERNATIVE",
    "description": "Lanzamiento anunciado oficialmente.",
    "record_club_url": "https://record.club/releases/albums/agnes-obel-the-meaning-of-flowers"
  },
  {
    "id": "ox4n87962wzldpez",
    "album_name": "Mule",
    "artist_name": "Orville Peck",
    "image_url": "https://cdn.rcrd.club/releases/ox4n87962wzldpez.webp?width=500",
    "release_date": "2026-09-18",
    "release_type": "ALBUM",
    "total_tracks": 10,
    "popularity_rank": 49,
    "popularity_raw": 14,
    "genre": "POP / ALTERNATIVE",
    "description": "Lanzamiento anunciado oficialmente.",
    "record_club_url": "https://record.club/releases/albums/orville-peck-mule"
  },
  {
    "id": "3qe68y0n1j2lrv01",
    "album_name": "Picnic at the Cemetery",
    "artist_name": "Bella Poarch",
    "image_url": "https://cdn.rcrd.club/releases/3qe68y0n1j2lrv01/3qe68yyv6108rv01.webp?v=45035702008&width=500",
    "release_date": "2026-09-18",
    "release_type": "ALBUM",
    "total_tracks": 10,
    "popularity_rank": 50,
    "popularity_raw": 13,
    "genre": "POP / ALTERNATIVE",
    "description": "Lanzamiento anunciado oficialmente.",
    "record_club_url": "https://record.club/releases/albums/bella-poarch-picnic-at-the-cemetery"
  }
];
