// scripts/popularMusicData.js
/**
 * Catálogo curado de los álbumes y artistas más buscados y escuchados en la historia
 * y tendencias actuales de la música para indexación en Sitemap (Programmatic SEO).
 */
const POPULAR_ALBUMS = [
  // Pop Global & Mainstream
  { album: 'SOUR', artist: 'Olivia Rodrigo' },
  { album: 'GUTS', artist: 'Olivia Rodrigo' },
  { album: 'Midnights', artist: 'Taylor Swift' },
  { album: '1989 (Taylor\'s Version)', artist: 'Taylor Swift' },
  { album: 'Folklore', artist: 'Taylor Swift' },
  { album: 'Evermore', artist: 'Taylor Swift' },
  { album: 'Red (Taylor\'s Version)', artist: 'Taylor Swift' },
  { album: 'Lover', artist: 'Taylor Swift' },
  { album: 'The Tortured Poets Department', artist: 'Taylor Swift' },
  { album: 'HIT ME HARD AND SOFT', artist: 'Billie Eilish' },
  { album: 'WHEN WE ALL FALL ASLEEP, WHERE DO WE GO?', artist: 'Billie Eilish' },
  { album: 'Happier Than Ever', artist: 'Billie Eilish' },
  { album: 'BRAT', artist: 'Charli xcx' },
  { album: 'Crash', artist: 'Charli xcx' },
  { album: 'The Rise and Fall of a Midwest Princess', artist: 'Chappell Roan' },
  { album: 'Short n\' Sweet', artist: 'Sabrina Carpenter' },
  { album: 'Emails I Can\'t Send', artist: 'Sabrina Carpenter' },
  { album: 'Future Nostalgia', artist: 'Dua Lipa' },
  { album: 'Radical Optimism', artist: 'Dua Lipa' },
  { album: 'Thank U, Next', artist: 'Ariana Grande' },
  { album: 'Eternal Sunshine', artist: 'Ariana Grande' },
  { album: 'Sweetener', artist: 'Ariana Grande' },
  { album: 'Renaissance', artist: 'Beyoncé' },
  { album: 'Cowboy Carter', artist: 'Beyoncé' },
  { album: 'Lemonade', artist: 'Beyoncé' },
  { album: 'After Hours', artist: 'The Weeknd' },
  { album: 'Dawn FM', artist: 'The Weeknd' },
  { album: 'Starboy', artist: 'The Weeknd' },
  { album: 'Fine Line', artist: 'Harry Styles' },
  { album: 'Harry\'s House', artist: 'Harry Styles' },
  { album: 'Something to Give Each Other', artist: 'Troye Sivan' },
  { album: 'Bewitched', artist: 'Laufey' },
  { album: 'The Secret of Us', artist: 'Gracie Abrams' },
  { album: 'Older', artist: 'Lizzy McAlpine' },
  { album: 'This Is How Tomorrow Moves', artist: 'Beabadoobee' },

  // Música en Español & Urbana
  { album: 'MOTOMAMI', artist: 'Rosalía' },
  { album: 'El Mal Querer', artist: 'Rosalía' },
  { album: 'Un Verano Sin Ti', artist: 'Bad Bunny' },
  { album: 'YHLQMDLG', artist: 'Bad Bunny' },
  { album: 'Nadie Sabe Lo Que Va A Pasar Mañana', artist: 'Bad Bunny' },
  { album: 'El Último Tour Del Mundo', artist: 'Bad Bunny' },
  { album: 'Saturno', artist: 'Rauw Alejandro' },
  { album: 'Cosa Nuestra', artist: 'Rauw Alejandro' },
  { album: 'Vice Versa', artist: 'Rauw Alejandro' },
  { album: 'Feliz Cumpleaños Ferxxo', artist: 'Feid' },
  { album: 'MOR, No Le Temas a la Oscuridad', artist: 'Feid' },
  { album: 'El Madrileño', artist: 'C. Tangana' },
  { album: 'Génesis', artist: 'Peso Pluma' },
  { album: 'Éxodo', artist: 'Peso Pluma' },
  { album: 'Orquídeas', artist: 'Kali Uchis' },
  { album: 'Isolation', artist: 'Kali Uchis' },
  { album: 'Sin Miedo (del Amor y Otros Demonios)', artist: 'Kali Uchis' },
  { album: 'Autopoiética', artist: 'Mon Laferte' },
  { album: 'De Todas las Flores', artist: 'Natalia Lafourcade' },
  { album: 'Hasta la Raíz', artist: 'Natalia Lafourcade' },
  { album: 'Bocanada', artist: 'Gustavo Cerati' },
  { album: 'Fuerza Natural', artist: 'Gustavo Cerati' },
  { album: 'Canción Animal', artist: 'Soda Stereo' },
  { album: 'Signos', artist: 'Soda Stereo' },
  { album: 'Daltónico', artist: 'Enjambre' },
  { album: 'Noches de Salón', artist: 'Enjambre' },
  { album: 'Moctezuma', artist: 'Porter' },
  { album: 'Memo Rex Commander', artist: 'Zoé' },
  { album: 'Prográmaton', artist: 'Zoé' },
  { album: 'Reptilectric', artist: 'Zoé' },
  { album: 'Río Salvaje', artist: 'Little Jesus' },
  { album: 'Submarine', artist: 'The Marías' },
  { album: 'Cinema', artist: 'The Marías' },
  { album: 'Marchita', artist: 'Silvana Estrada' },
  { album: 'París Texas', artist: 'Kevin Kaarl' },
  { album: 'eduardo', artist: 'Ed Maverick' },

  // Hip Hop & R&B
  { album: 'To Pimp a Butterfly', artist: 'Kendrick Lamar' },
  { album: 'good kid, m.A.A.d city', artist: 'Kendrick Lamar' },
  { album: 'DAMN.', artist: 'Kendrick Lamar' },
  { album: 'GNX', artist: 'Kendrick Lamar' },
  { album: 'Blonde', artist: 'Frank Ocean' },
  { album: 'Channel Orange', artist: 'Frank Ocean' },
  { album: 'IGOR', artist: 'Tyler, The Creator' },
  { album: 'CALL ME IF YOU GET LOST', artist: 'Tyler, The Creator' },
  { album: 'Flower Boy', artist: 'Tyler, The Creator' },
  { album: 'CHROMAKOPIA', artist: 'Tyler, The Creator' },
  { album: 'SOS', artist: 'SZA' },
  { album: 'Ctrl', artist: 'SZA' },
  { album: 'ASTROWORLD', artist: 'Travis Scott' },
  { album: 'UTOPIA', artist: 'Travis Scott' },
  { album: 'Rodeo', artist: 'Travis Scott' },
  { album: 'My Beautiful Dark Twisted Fantasy', artist: 'Kanye West' },
  { album: 'Graduation', artist: 'Kanye West' },
  { album: 'The College Dropout', artist: 'Kanye West' },
  { album: 'Swimming', artist: 'Mac Miller' },
  { album: 'Circles', artist: 'Mac Miller' },
  { album: 'Take Care', artist: 'Drake' },
  { album: 'Views', artist: 'Drake' },
  { album: 'Gemini Rights', artist: 'Steve Lacy' },
  { album: 'Madvillainy', artist: 'Madlib & MF DOOM' },
  { album: 'MM..FOOD', artist: 'MF DOOM' },
  { album: 'Illmatic', artist: 'Nas' },
  { album: 'Enter the Wu-Tang (36 Chambers)', artist: 'Wu-Tang Clan' },
  { album: 'Ready to Die', artist: 'The Notorious B.I.G.' },
  { album: 'The Marshall Mathers LP', artist: 'Eminem' },
  { album: '2014 Forest Hills Drive', artist: 'J. Cole' },
  { album: 'Sometimes I Might Be Introvert', artist: 'Little Simz' },

  // Indie, Rock & Alternativo
  { album: 'OK Computer', artist: 'Radiohead' },
  { album: 'Kid A', artist: 'Radiohead' },
  { album: 'In Rainbows', artist: 'Radiohead' },
  { album: 'The Bends', artist: 'Radiohead' },
  { album: 'Currents', artist: 'Tame Impala' },
  { album: 'The Slow Rush', artist: 'Tame Impala' },
  { album: 'Lonerism', artist: 'Tame Impala' },
  { album: 'AM', artist: 'Arctic Monkeys' },
  { album: 'Whatever People Say I Am, That\'s What I\'m Not', artist: 'Arctic Monkeys' },
  { album: 'Tranquility Base Hotel & Casino', artist: 'Arctic Monkeys' },
  { album: 'Is This It', artist: 'The Strokes' },
  { album: 'Room on Fire', artist: 'The Strokes' },
  { album: 'The New Abnormal', artist: 'The Strokes' },
  { album: 'Born to Die', artist: 'Lana Del Rey' },
  { album: 'Norman Fucking Rockwell!', artist: 'Lana Del Rey' },
  { album: 'Did you know that there\'s a tunnel under Ocean Blvd', artist: 'Lana Del Rey' },
  { album: 'Melodrama', artist: 'Lorde' },
  { album: 'Pure Heroine', artist: 'Lorde' },
  { album: 'Punisher', artist: 'Phoebe Bridgers' },
  { album: 'the record', artist: 'boygenius' },
  { album: 'Charm', artist: 'Clairo' },
  { album: 'Immunity', artist: 'Clairo' },
  { album: 'Sling', artist: 'Clairo' },
  { album: 'Titanic Rising', artist: 'Weyes Blood' },
  { album: 'Blue Rev', artist: 'Alvvays' },
  { album: 'Jubilee', artist: 'Japanese Breakfast' },
  { album: 'Be the Cowboy', artist: 'Mitski' },
  { album: 'The Land Is Inhospitable and So Are We', artist: 'Mitski' },
  { album: 'Bloom', artist: 'Beach House' },
  { album: 'Depression Cherry', artist: 'Beach House' },
  { album: 'Oncle Jazz', artist: 'Men I Trust' },
  { album: 'Romance', artist: 'Fontaines D.C.' },
  { album: 'Skinty Fia', artist: 'Fontaines D.C.' },
  { album: 'Only God Was Above Us', artist: 'Vampire Weekend' },
  { album: 'Modern Vampires of the City', artist: 'Vampire Weekend' },
  { album: 'Demon Days', artist: 'Gorillaz' },
  { album: 'Plastic Beach', artist: 'Gorillaz' },
  { album: 'Random Access Memories', artist: 'Daft Punk' },
  { album: 'Discovery', artist: 'Daft Punk' },
  { album: 'Sound of Silver', artist: 'LCD Soundsystem' },
  { album: 'Turn On the Bright Lights', artist: 'Interpol' },
  { album: 'Funeral', artist: 'Arcade Fire' },
  { album: 'The Suburbs', artist: 'Arcade Fire' },
  { album: 'For Emma, Forever Ago', artist: 'Bon Iver' },
  { album: '22, A Million', artist: 'Bon Iver' },
  { album: 'Carrie & Lowell', artist: 'Sufjan Stevens' },
  { album: 'Javelin', artist: 'Sufjan Stevens' },
  { album: 'Fetch the Bolt Cutters', artist: 'Fiona Apple' },
  { album: 'This Is Why', artist: 'Paramore' },
  { album: 'After Laughter', artist: 'Paramore' },
  { album: 'Hot Fuss', artist: 'The Killers' },
  { album: 'A Rush of Blood to the Head', artist: 'Coldplay' },
  { album: 'Parachutes', artist: 'Coldplay' },
  { album: 'Viva la Vida or Death and All His Friends', artist: 'Coldplay' },

  // Clásicos Legendarios
  { album: 'The Dark Side of the Moon', artist: 'Pink Floyd' },
  { album: 'Wish You Were Here', artist: 'Pink Floyd' },
  { album: 'The Wall', artist: 'Pink Floyd' },
  { album: 'Abbey Road', artist: 'The Beatles' },
  { album: 'Sgt. Pepper\'s Lonely Hearts Club Band', artist: 'The Beatles' },
  { album: 'Revolver', artist: 'The Beatles' },
  { album: 'Rumours', artist: 'Fleetwood Mac' },
  { album: 'Nevermind', artist: 'Nirvana' },
  { album: 'In Utero', artist: 'Nirvana' },
  { album: 'The Rise and Fall of Ziggy Stardust and the Spiders from Mars', artist: 'David Bowie' },
  { album: 'Heroes', artist: 'David Bowie' },
  { album: 'Blackstar', artist: 'David Bowie' },
  { album: 'Thriller', artist: 'Michael Jackson' },
  { album: 'Bad', artist: 'Michael Jackson' },
  { album: 'Purple Rain', artist: 'Prince' },
  { album: 'Songs in the Key of Life', artist: 'Stevie Wonder' },
  { album: 'Innervisions', artist: 'Steviet Wonder' },
  { album: 'What\'s Going On', artist: 'Marvin Gaye' },
  { album: 'Pet Sounds', artist: 'The Beach Boys' },
  { album: 'Back to Black', artist: 'Amy Winehouse' },
  { album: 'Disintegration', artist: 'The Cure' },
  { album: 'Unknown Pleasures', artist: 'Joy Division' },
  { album: 'The Queen Is Dead', artist: 'The Smiths' },
  { album: 'Definitely Maybe', artist: 'Oasis' },
  { album: '(What\'s the Story) Morning Glory?', artist: 'Oasis' },
  { album: 'American Idiot', artist: 'Green Day' },
  { album: 'Dookie', artist: 'Green Day' },
  { album: 'Hybrid Theory', artist: 'Linkin Park' },
  { album: 'Meteora', artist: 'Linkin Park' },
  { album: 'Californication', artist: 'Red Hot Chili Peppers' },
  { album: 'Blood Sugar Sex Magik', artist: 'Red Hot Chili Peppers' },
  { album: 'The Colour and the Shape', artist: 'Foo Fighters' },
  { album: 'White Pony', artist: 'Deftones' },
  { album: 'Toxicity', artist: 'System of a Down' },
  { album: 'Master of Puppets', artist: 'Metallica' },
  { album: 'Metallica (The Black Album)', artist: 'Metallica' },
  { album: 'Led Zeppelin IV', artist: 'Led Zeppelin' },
  { album: 'Sticky Fingers', artist: 'The Rolling Stones' },
  { album: 'Exile on Main St.', artist: 'The Rolling Stones' },
  { album: 'Highway 61 Revisited', artist: 'Bob Dylan' },
  { album: 'Blood on the Tracks', artist: 'Bob Dylan' },
  { album: 'Kind of Blue', artist: 'Miles Davis' },
  { album: 'A Love Supreme', artist: 'John Coltrane' },
  { album: 'Loveless', artist: 'My Bloody Valentine' },
  { album: 'Mezzanine', artist: 'Massive Attack' },
  { album: 'Dummy', artist: 'Portishead' },
  { album: 'Homogenic', artist: 'Björk' },
  { album: 'Vespertine', artist: 'Björk' },
];

module.exports = {
  POPULAR_ALBUMS,
};
